// grain engine · query surface · argv, repository and store resolution, auto-refresh, the seed file and the worktree/HEAD comparison every command answers from
// Split out of grain.mjs (ticket 124): the statements below are the ones that stood there, unchanged.
import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  statSync,
  writeFileSync,
  realpathSync,
} from 'node:fs';
import { join, relative, resolve, isAbsolute, dirname, basename, dirname as pdirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { ENGINE_VERSION, EXTR_V, MODEL_V, GRAMMAR_DIR, GRAMMARS, HARD_EXCL } from './config.mjs';
import { learn, walkFiles, toPosix } from './core.mjs';
import { loadHistory, headSha, headTree, gitOk, isShallow } from './history.mjs';
import { createHash } from 'node:crypto';
import {  } from './core.mjs';

const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const BIN = join(PLUGIN_ROOT, 'bin', 'grain.mjs');
// ----- argv -----
export function parseArgv(argv) {
  const opts = {};
  const args = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--') {
      args.push(...argv.slice(i + 1));
      break;
    }
    if (a.startsWith('--')) {
      const [k, ...v] = a.slice(2).split('=');
      if (v.length) opts[k] = v.join('=');
      else if (
        [
          'repo',
          'top',
          'minbits',
          'as',
          'content',
          'mode',
          'map-rows',
          'out',
          'max-sites',
          'surfaces',
          'instead-of',
          'never-imports',
          'weight',
          'topic',
          'note',
          'author',
          'range',
          'on',
          'last',
          'holdout',
        ].includes(k) &&
        argv[i + 1] !== undefined &&
        !argv[i + 1].startsWith('--')
      )
        opts[k] = argv[++i];
      // `--json` is a bare flag on every other command (`grain check --json src/a.ts` must keep its file
      // argument), and the path to write on `propose`, whose report is too big to interleave with its own text
      else if (k === 'json' && args[0] === 'propose' && argv[i + 1] !== undefined && !argv[i + 1].startsWith('--'))
        opts[k] = argv[++i];
      else opts[k] = true;
    } else args.push(a);
  }
  return { cmd: args[0], args: args.slice(1), opts };
}
// ----- repo + store -----
export function findRoot(opts) {
  const start = resolve(opts.repo || process.cwd());
  if (opts.repo && !existsSync(start)) throw new Error(`no such directory: ${start}`);
  try {
    return {
      root: execFileSync('git', ['-C', start, 'rev-parse', '--show-toplevel'], {
        stdio: ['ignore', 'pipe', 'ignore'],
      })
        .toString()
        .trim(),
      git: true,
    };
  } catch {
    return { root: start, git: false };
  }
}
// Two stores under <repo>/.grain/ (the spec's store triad minus local state, which a query tool does not keep):
//   .grain/cache/   rebuildable, gitignored — model.json, meta.json, history.json, blobs/   (safe to wipe: `rm -rf .grain/cache`)
//   .grain/         committed inputs — reserved for maintainer seeds (seeds.jsonl) and their audit trail (decisions.jsonl)
// .grain/.gitignore ignores `cache/`, so nothing generated can be committed even when the user never touches the root .gitignore.
export function storeFor(root) {
  const base = join(root, '.grain');
  const dir = join(base, 'cache');
  return {
    base,
    dir,
    modelPath: join(dir, 'model.json'),
    metaPath: join(dir, 'meta.json'),
    historyPath: join(dir, 'history.json'),
    blobsDir: join(dir, 'blobs'),
    scopesPath: join(dir, 'scopes.json'),
    treePath: join(dir, 'tree.json'),
    seedsPath: join(base, 'seeds.jsonl'),
  };
}
function ensureStore(root, store) {
  mkdirSync(store.dir, { recursive: true });
  const gi = join(store.base, '.gitignore');
  if (!existsSync(gi)) {
    writeFileSync(
      gi,
      '# generated by grain — the cache is disposable; everything else in .grain/ is meant to be committed\ncache/\n'
    );
    console.error('[grain] created .grain/.gitignore (ignores .grain/cache/)');
  }
}
export const atomicWrite = (p, d) => {
  const t = p + '.tmp-' + process.pid;
  writeFileSync(t, d);
  renameSync(t, p);
};
export const readJson = p => {
  try {
    return JSON.parse(readFileSync(p, 'utf8'));
  } catch {
    return null;
  }
};
const grammarStamp = () => {
  const m = readJson(join(GRAMMAR_DIR, 'manifest.json'));
  return m
    ? Object.entries(m)
        .map(([g, v]) => g + '@' + v.version)
        .join(',')
    : GRAMMARS.join(',');
};
// cheap signature of the tree for repositories without git: (path,size,mtime) of every code file
function treeSig(root) {
  let h = 2166136261;
  const mix = s => {
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
  };
  for (const rel of [...walkFiles(root, root)].sort()) {
    try {
      const st = statSync(join(root, rel));
      mix(rel + ':' + st.size + ':' + st.mtimeMs);
    } catch {}
  }
  return (h >>> 0).toString(16);
}
export const short = sha => (sha ? sha.slice(0, 7) : 'no-git');
export const log = (...a) => console.error('[grain]', ...a);
/**
 * Freshness protocol (runs before every query):
 *   same HEAD as indexed → answer immediately; new commits on the same line → incremental update, then answer;
 *   divergent history → full rebuild on the warm blob cache (or, with --no-refresh, answer with a STALE banner);
 *   no index → build. Worktree edits never trigger a rebuild (the norm is the accepted past — by design).
 */
export async function ensureFresh({ root, isGit, store, opts, want = 'refresh' }) {
  const head = isGit ? headSha(root) : null;
  const meta = readJson(store.metaPath);
  const model = existsSync(store.modelPath) ? readJson(store.modelPath) : null;
  // extractOk gates the tree/blob extraction cache alone (engine+extractor+grammars — never MODEL_V: model schema
  // is a pure downstream reading of already-extracted scopes, §028); versionOk additionally requires the model
  // schema to match, and gates the "no work at all" fast path plus the STALE banner — a MODEL_V-only staleness
  // must still force a real relearn, it just gets to reuse a version-current tree cache while doing it.
  const extractOk =
    meta && meta.engine === ENGINE_VERSION && meta.extractor === EXTR_V && meta.grammars === grammarStamp();
  const versionOk = extractOk && (meta.model || '') === MODEL_V;
  const { seeds, boundaries, waivers } = readSeeds(store);
  const seedsHash = hashSeeds({ seeds, boundaries, waivers });
  const sig = isGit ? null : treeSig(root);
  const cachedWithHistory = meta && meta.historyMode && meta.historyMode !== 'none';
  const cachedNoHistoryByFlag =
    meta && meta.historyMode === 'none' && meta.historyReason === '--no-history flag';
  const cachedShallow = meta && meta.historyReason === 'shallow clone — history unavailable, weights flat';
  const nowUnshallow = cachedShallow && isGit && !isShallow(root); // §G13: the cache says shallow, but the repo isn't anymore — that alone must invalidate freshness, even though headSha/version/seeds all still match
  const fresh =
    model &&
    versionOk &&
    (meta.seedsHash || '') === seedsHash &&
    (isGit ? meta.headSha === head : meta.treeSig === sig) && // a changed seeds file re-mines like a new commit would
    !(cachedNoHistoryByFlag && !opts['no-history']) && // §G12 (symmetric case): a cache built under --no-history must not silently serve a no-flag call as if it had full history — force a real rebuild instead
    !nowUnshallow;
  const banner = [];
  if (fresh && want !== 'force') {
    if (opts['no-history'] && cachedWithHistory) {
      // §G12: a per-invocation --no-history must not be silently ignored by an otherwise-fresh WITH-history cache
      const treeCache = readJson(store.treePath);
      const tree =
        isGit && head
          ? headTree(root, { skip: (rel, sha) => !!(treeCache && treeCache[sha + '|' + rel]) })
          : null;
      const { model: m2 } = await learn({ root, H: null, log, tree, treeCache, seeds, boundaries, waivers });
      return {
        model: m2,
        meta: { ...meta, historyMode: 'none', historyReason: '--no-history flag' },
        head,
        banner,
      };
    } // in-memory only — the persisted store is NEVER touched here, the flag is per-invocation, not a change to indexed state
    return { model, meta, head, banner };
  }
  if (want === 'none') {
    // caller refuses to rebuild (hook path, or --no-refresh): answer stale, never silently
    if (!model)
      return {
        model: null,
        meta,
        head,
        banner: ['NO INDEX: run `grain refresh` (or any query) to build it'],
      };
    banner.push(
      `STALE: indexed at ${short(meta?.headSha)}, HEAD is ${short(head)}${versionOk ? '' : ' (engine/grammar version changed)'} — run \`grain refresh\``
    );
    return { model, meta, head, banner, stale: true };
  }
  ensureStore(root, store);
  const t0 = Date.now();
  let H = null,
    hist = { mode: 'none', reason: isGit ? '--no-history flag' : 'not a git repository (or no commits yet)' };
  if (isGit && !opts['no-history']) {
    hist = await loadHistory({
      gitdir: root,
      store,
      log,
      full: (want === 'force' && !!opts.full) || !versionOk,
    });
    H = hist.H;
    if (hist.mode === 'none') log(`history: ${hist.reason}`);
  }
  log(
    `indexing ${root} (${hist.mode === 'incremental' ? 'incremental' : hist.mode === 'unchanged' ? 'history unchanged' : hist.mode === 'full' ? 'full history' : 'no history'})`
  );
  const treeCache = extractOk ? readJson(store.treePath) : null; // (blob sha, path) → extracted scopes, from the previous index
  const tree =
    isGit && head
      ? headTree(root, { skip: (rel, sha) => !!(treeCache && treeCache[sha + '|' + rel]) })
      : null;
  const {
    model: m2,
    ms,
    scopes,
    rawScopes,
    treeCacheOut,
  } = await learn({ root, H, log, tree, treeCache, seeds, boundaries, waivers });
  atomicWrite(store.modelPath, JSON.stringify(m2));
  if (tree) atomicWrite(store.treePath, JSON.stringify(treeCacheOut));
  else atomicWrite(store.scopesPath, JSON.stringify(rawScopes));
  const meta2 = {
    engine: ENGINE_VERSION,
    extractor: EXTR_V,
    model: MODEL_V,
    grammars: grammarStamp(),
    headSha: head,
    treeSig: sig,
    seedsHash,
    historyMode: hist.mode,
    historyReason: hist.reason || null,
    builtAt: new Date().toISOString(),
    buildMs: Date.now() - t0,
    scopes,
  };
  atomicWrite(store.metaPath, JSON.stringify(meta2, null, 1));
  log(
    `indexed in ${((Date.now() - t0) / 1000).toFixed(1)}s: ${m2.partitions.reduce((a, p) => a + p.facts.length, 0)} conventions, ${scopes} scopes, learn ${ms}ms`
  );
  return { model: m2, meta: meta2, head, banner };
}
// exemplar re-validation at render time is a memoized existence check (never a re-parse)
export const existsMemo = root => {
  const m = new Map();
  return rel => {
    if (!m.has(rel)) m.set(rel, existsSync(join(root, rel)));
    return m.get(rel);
  };
};
// worktree vs HEAD for one file: dirty ⇔ untracked, or content differs from the HEAD blob
export function fileDirty(root, rel, isGit, diffArgs) {
  if (!isGit) return true;
  if (!diffArgs && !gitOk(root, ['ls-files', '--error-unmatch', '--', rel])) return true;
  return !gitOk(root, ['diff', '--quiet', ...(diffArgs || ['HEAD']), '--', rel]);
}
// (§024c) whether ANY part of the worktree differs from HEAD — unlike fileDirty (one file, used by check/review/
// spectrum to decide what to actually READ), this never gates what a HEAD-reading command reads; it only decides
// whether that command owes the disclosure below. `git status --porcelain` covers staged, unstaged and untracked
// in one call and, unlike `git diff HEAD`, needs no HEAD to compare against (so it stays correct on a repo with
// zero commits, where `isGit` is still true). HARD_EXCL (grain's own store, `.grain/`) is filtered out the same
// way `reviewFileList` filters it from a real change list — otherwise a repo that has never committed the
// `.grain/.gitignore` this tool writes on its first run would show as permanently dirty on every query, which is
// noise about grain's own bookkeeping, not the user's code.
export function repoDirty(root, isGit) {
  if (!isGit) return false;
  let out;
  try {
    out = execFileSync('git', ['-C', root, 'status', '--porcelain'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
  } catch {
    return false;
  }
  return out.split('\n').some(line => {
    const p = toPosix(line.slice(3));
    return p && !HARD_EXCL.test(p);
  });
}
// the worktree lines this file changed against HEAD (untracked ⇒ every line; clean ⇒ none): `check` reports deviations in
// the caller's own change first and folds pre-existing ones into a count — measured: 11 pre-existing deviations and 0 about
// the change on one flask file was 1.5k tokens of noise
export function changedRanges(root, rel, isGit, diffArgs) {
  if (!isGit) return null;
  if (!diffArgs && !gitOk(root, ['ls-files', '--error-unmatch', '--', rel])) return [[1, Infinity]];
  let out;
  try {
    out = execFileSync('git', ['-C', root, 'diff', '-U0', ...(diffArgs || ['HEAD']), '--', rel], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
  } catch {
    return null;
  }
  const ranges = [];
  for (const m of out.matchAll(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/gm)) {
    const a = +m[1],
      n = m[2] === undefined ? 1 : +m[2];
    ranges.push(n === 0 ? [a, a + 1] : [a, a + n - 1]);
  } // a pure deletion touches the line after its point (the class whose decorator was deleted)
  return ranges;
}
export function canonicalize(p) {
  // realpath through the deepest EXISTING ancestor — handles a path not yet on disk (a
  // pre-write path) and OS symlinks (macOS /tmp -> /private/tmp) that would otherwise put a valid path "outside"
  // its own repository; shared by relPath and check-hook's PreToolUse path resolution
  try {
    return realpathSync(p);
  } catch {
    let d2 = p;
    const tail = [];
    while (!existsSync(d2)) {
      tail.unshift(basename(d2));
      const nd = pdirname(d2);
      if (nd === d2) break;
      d2 = nd;
    }
    try {
      return join(realpathSync(d2), ...tail);
    } catch {
      return p;
    }
  }
}
export function relPath(root, p) {
  let abs;
  if (isAbsolute(p)) abs = canonicalize(p);
  else {
    const underRoot = resolve(root, p),
      underCwd = resolve(process.cwd(), p);
    abs = existsSync(underRoot)
      ? underRoot
      : existsSync(underCwd) && !relative(root, underCwd).startsWith('..')
        ? underCwd
        : underRoot;
  } // neither exists (or the cwd match would itself escape root): fall back to root-relative so a
  // distinct "no such file" check downstream catches it, not a false "outside"
  const rel = toPosix(relative(root, abs));
  if (rel.startsWith('..')) throw new Error(`${p} is outside the repository ${root}`);
  return rel;
}
// ----- seeds (steering): .grain/seeds.jsonl, committed; one maintainer decision per line -----
export function readSeeds(store) {
  const out = [];
  const boundaries = [];
  const waivers = [];
  if (existsSync(store.seedsPath))
    for (const line of readFileSync(store.seedsPath, 'utf8').split('\n')) {
      const t = line.trim();
      if (!t || t.startsWith('#')) continue;
      try {
        const j = JSON.parse(t);
        if (j && j.boundary && j.boundary.from && j.boundary.to)
          boundaries.push({
            id: j.id,
            boundary: { from: j.boundary.from.replace(/\/$/, ''), to: j.boundary.to.replace(/\/$/, '') },
            note: j.note || '',
            author: j.author || '',
            createdAt: j.createdAt || '',
          });
        else if (j && j.waiver && j.waiver.path && j.waiver.pid)
          waivers.push({
            id: j.id,
            path: j.waiver.path,
            name: j.waiver.name || '',
            pid: j.waiver.pid,
            note: j.note || '',
            author: j.author || '',
            createdAt: j.createdAt || '',
          });
        else if (j && j.scope && j.scope.path && Array.isArray(j.surfaces) && j.surfaces.length)
          out.push({
            id: j.id,
            path: j.scope.path,
            name: j.scope.name,
            pids: j.surfaces.concat(j.retired || []),
            retired: j.retired || [],
            weight: +j.weight || 8,
            topic: j.topic || '',
            note: j.note || '',
            author: j.author || '',
            createdAt: j.createdAt || '',
            baseline: j.baseline || null,
          });
      } catch {
        log(`seeds.jsonl: skipped an unparsable line: ${t.slice(0, 60)}`);
      }
    }
  return { seeds: out, boundaries, waivers };
}
const hashSeeds = ({ seeds, boundaries, waivers = [] }) =>
  seeds.length || boundaries.length || waivers.length
    ? createHash('sha256')
        .update(JSON.stringify([seeds, boundaries, waivers]))
        .digest('hex')
        .slice(0, 16)
    : '';
// the indexed scopes of HEAD (tree cache, or the scope snapshot of a git-less repo); a missing cache is rebuilt once
export async function loadScopes({ root, isGit, store, opts }) {
  let treeCache = readJson(store.treePath);
  let snap = treeCache ? null : readJson(store.scopesPath);
  if (!treeCache && !snap) {
    log('scope cache missing — rebuilding it');
    await ensureFresh({ root, isGit, store, opts, want: 'force' });
    treeCache = readJson(store.treePath);
    snap = treeCache ? null : readJson(store.scopesPath);
  }
  return treeCache ? Object.values(treeCache).flatMap(v => (Array.isArray(v) ? v : v.s)) : snap || [];
}
