// grain engine · query surface · `spectrum`, `seed` and `decide` — the maintainer decisions that steer the norm
// Split out of grain.mjs (ticket 124): the statements below are the ones that stood there, unchanged.
import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { spectrum, part } from './core.mjs';
import { createHash } from 'node:crypto';
import {
  hydrateScope,
  applyVocab,
  partitionFor,
  verbalize as verb2,
  baselineShare,
  heritageKindOf,
} from './core.mjs';
import { atomicWrite, fileDirty, loadScopes, log, readJson, readSeeds, relPath } from './grain-context.mjs';

export async function cmdSpectrum({ model, root, isGit, args, opts, stamp, store }) {
  if (!args[0]) throw new Error('usage: grain spectrum <file> [--minbits N] [--top N]');
  const rel = relPath(root, args[0]);
  const treeCache = readJson(store.treePath); // (sha|path) → { s: scopes, r: relation facts } of HEAD's files
  const scopesAll = treeCache
    ? Object.values(treeCache).flatMap(v => (Array.isArray(v) ? v : v.s))
    : readJson(store.scopesPath);
  const r = await spectrum({
    model,
    root,
    rel,
    minBits: opts.minbits !== undefined ? +opts.minbits : 0,
    top: +opts.top || 0,
    scopesAll,
  });
  return [...r.lines, stamp(fileDirty(root, rel, isGit))];
}
function appendDecision(store, rec) {
  appendFileSync(join(store.base, 'decisions.jsonl'), JSON.stringify(rec) + '\n');
}
function ensureSeedAttrs(store) {
  const p = join(store.base, '.gitattributes');
  if (existsSync(p)) return;
  writeFileSync(
    p,
    '# generated by grain: decisions from two branches merge line by line\nseeds.jsonl merge=union\ndecisions.jsonl merge=union\n'
  );
  log('created .grain/.gitattributes (merge=union for seeds.jsonl and decisions.jsonl)');
}
// the surfaces a scope carries right now, with values — what a maintainer picks from when recording a steer
async function scopeSurfaces({ model, store, rel, name, root, isGit, opts }) {
  const all = await loadScopes({ root, isGit, store, opts });
  const part = partitionFor(model, rel);
  if (!part) return { error: `no partition covers ${rel}` };
  const cands = all.filter(s => s.rel === rel && s.kind !== 'module').map(hydrateScope);
  if (!cands.length) return { error: `no scopes indexed for ${rel} (is it committed and parsed?)` };
  const s = name ? cands.find(x => x.name === name) : cands.length === 1 ? cands[0] : null;
  if (!s)
    return {
      error: name
        ? `no scope named ${name} in ${rel}`
        : `pick one scope of ${rel}: ${cands.map(x => `${x.kind} ${x.name} (line ${x.line})`).join(' · ')}`,
      cands,
    };
  applyVocab(s, part.vocab);
  const positive = Object.entries(s.preds).filter(
    ([pid, v]) => v !== 'false' && !/^auto\.(has|stshape|dir\d|mod)/.test(pid)
  );
  return {
    scope: s,
    surfaces: positive.map(([pid, v]) => ({
      pid,
      value: v,
      statement: verb2({ pid, exp: v, kind: s.kind, heritageKind: heritageKindOf(pid, model) }, [s.name]),
    })),
  };
}
// `decide` and `seed` are one command under two names: `decide` names the three kinds of decision a maintainer can
// record (steer · boundary · waive), `seed` is the original spelling and keeps its own nouns in its own messages.
const DECIDE_SUBS = { steer: 'add', boundary: 'add-boundary' };
export const cmdDecide = ctx =>
  cmdSeed({ ...ctx, args: [DECIDE_SUBS[ctx.args[0]] || ctx.args[0], ...ctx.args.slice(1)] });
async function cmdSeed({ model, root, isGit, store, args, opts, stamp }) {
  const sub = args[0];
  if (sub === 'list') {
    const { seeds, boundaries, waivers } = readSeeds(store);
    if (!seeds.length && !boundaries.length && !waivers.length)
      return [
        'no seeds — `grain seed add <path>#<name> --surfaces <pid,…> --note "…"` (pattern) or `grain seed add-boundary <from> --never-imports <to> --note "…"` (architecture) records a maintainer decision in .grain/seeds.jsonl',
        stamp(),
      ];
    return [
      ...seeds.map(
        sd =>
          `${sd.id}  ${sd.path}#${sd.name}  ${sd.pids.join(',')}  weight ${sd.weight}${sd.topic ? `  topic "${sd.topic}"` : ''}${sd.note ? `  — ${sd.note}` : ''}  (${[sd.author, sd.createdAt].filter(Boolean).join(' ')})`
      ),
      ...boundaries.map(
        bd =>
          `${bd.id}  boundary: ${bd.boundary.from}/ never imports ${bd.boundary.to}/${bd.note ? `  — ${bd.note}` : ''}  (${[bd.author, bd.createdAt].filter(Boolean).join(' ')})`
      ),
      ...waivers.map(
        wv =>
          `${wv.id}  waiver: ${wv.path}#${wv.name} on ${wv.pid}${wv.note ? `  — ${wv.note}` : ''}  (${[wv.author, wv.createdAt].filter(Boolean).join(' ')})`
      ),
      stamp(),
    ];
  }
  if (sub === 'rm') {
    const id = args[1];
    if (!id) throw new Error('usage: grain seed rm <id>');
    const lines = existsSync(store.seedsPath) ? readFileSync(store.seedsPath, 'utf8').split('\n') : [];
    const kept = lines.filter(l => {
      try {
        return l.trim() && JSON.parse(l).id !== id;
      } catch {
        return !!l.trim();
      }
    });
    if (kept.length === lines.filter(l => l.trim()).length) throw new Error(`no seed with id ${id}`);
    atomicWrite(store.seedsPath, kept.join('\n') + (kept.length ? '\n' : ''));
    appendDecision(store, {
      action: 'rm',
      id,
      at: new Date().toISOString().slice(0, 10),
      by: opts.author || process.env.USER || '',
    });
    return [`removed seed ${id} — the next query re-mines without it`, stamp()];
  }
  if (sub === 'add') {
    const target = args[1];
    if (!target)
      throw new Error(
        'usage: grain seed add <path>[#<scope name>] [--surfaces <pid,…>] [--instead-of <pid,…>] [--weight N] [--topic "…"] [--note "…"] [--author X]'
      );
    const [p0, name] = target.split('#');
    const rel = relPath(root, p0);
    const r = await scopeSurfaces({ model, store, rel, name, root, isGit, opts });
    if (r.error) return [r.error, stamp()];
    const want = opts.surfaces
      ? String(opts.surfaces)
          .split(',')
          .map(x => x.trim())
          .filter(Boolean)
      : [];
    const retire = opts['instead-of']
      ? String(opts['instead-of'])
          .split(',')
          .map(x => x.trim())
          .filter(Boolean)
      : [];
    if (!want.length)
      return [
        `${rel}#${r.scope.name} (${r.scope.kind}, line ${r.scope.line}) carries these surfaces — choose which to promote and re-run with --surfaces <pid,…> (optionally --instead-of <pid,…> naming what it replaces):`,
        ...r.surfaces.map(x => `  ${x.pid} = ${x.value}    ${x.statement}`),
        '(a seed without surfaces is refused: grain will not guess which property you meant)',
        stamp(),
      ];
    const bad = want.filter(pid => r.scope.preds[pid] === undefined);
    if (bad.length)
      throw new Error(
        `${rel}#${r.scope.name} has no surface ${bad.join(', ')} — run \`grain seed add ${target}\` without --surfaces to see them`
      );
    // the retired surface must be one the exemplar does NOT carry (its value there is 'false'): the seed then mutes the old
    // rule wherever it fires and `check` reports carriers of the retired value as departing from the decision
    const badR = retire.filter(pid => r.scope.preds[pid] !== 'false');
    if (badR.length)
      throw new Error(
        `--instead-of ${badR.join(', ')}: the exemplar ${r.scope.name} ${r.scope.preds[badR[0]] === undefined ? 'has no such surface' : 'itself carries that value'} — name a surface the exemplar has retired (its value on the exemplar is 'false')`
      );
    const createdAt = new Date().toISOString().slice(0, 10);
    const author = opts.author || process.env.USER || '';
    const id = createHash('sha256')
      .update([rel, r.scope.name, want.concat(retire).join(','), author, createdAt].join('|'))
      .digest('hex')
      .slice(0, 8);
    if (readSeeds(store).seeds.some(sd => sd.id === id))
      return [
        `seed ${id} already exists for ${rel}#${r.scope.name} on ${want.join(',')} — \`grain seed rm ${id}\` first to change it`,
        stamp(),
      ];
    // a creation-time snapshot of how widely the FIRST promoted surface was already practiced — read back by
    // `report`/`where` so a later reader can see whether adoption has moved since the decision was made, without
    // keeping their own notes. null when the exemplar's partition never mined a partition-wide (`_all:`) fact for
    // this (kind, pid) — a brand-new pattern, or one whose accepted convention lives only at a group/directory
    // context this snapshot deliberately does not chase (see `baselineShare` in core.mjs for the trade-off)
    const baseline = (() => {
      const b = baselineShare(model, rel, r.scope.kind, want[0], r.scope.preds[want[0]]);
      return b ? { ...b, at: createdAt } : null;
    })();
    const rec = {
      id,
      scope: { path: rel, name: r.scope.name },
      surfaces: want,
      retired: retire,
      weight: +opts.weight || 8,
      topic: opts.topic || '',
      note: opts.note || '',
      author,
      createdAt,
      baseline,
    };
    mkdirSync(store.base, { recursive: true });
    ensureSeedAttrs(store);
    appendFileSync(store.seedsPath, JSON.stringify(rec) + '\n');
    appendDecision(store, { action: 'add', id, at: createdAt, by: author, note: rec.note });
    return [
      `recorded seed ${id} in .grain/seeds.jsonl — ${want.map(pid => verb2({ pid, exp: r.scope.preds[pid], kind: r.scope.kind, heritageKind: heritageKindOf(pid, model) }, [r.scope.name])).join('; ')} (weight ${rec.weight}, capped at half the real population of each cell). Commit .grain/seeds.jsonl and .grain/decisions.jsonl; the next query re-mines with it.`,
      stamp(),
    ];
  }
  // a waiver excuses ONE scope from ONE convention. Its key is (path, name, pid) and `checkFile` matches it by that
  // key alone — so an ambiguous target (two scopes of one file sharing a name: overloads, methods of sibling classes)
  // would silently waive the wrong one. Refuse it here, with `seed add`'s own wording for the same situation.
  if (sub === 'waive') {
    const target = args[1];
    const pid = typeof opts.on === 'string' ? opts.on : null;
    if (!target || !pid)
      throw new Error('usage: grain decide waive <path>#<name> --on <pid> --note "…" [--author X]');
    const [p0, name] = target.split('#');
    const rel = relPath(root, p0);
    if (!name)
      throw new Error(
        `grain decide waive names one scope: ${rel}#<scope name> (a waiver excuses a scope, never a whole file)`
      );
    const all = await loadScopes({ root, isGit, store, opts });
    const cands = all.filter(s => s.rel === rel && s.kind !== 'module' && s.name === name);
    if (!cands.length) return [`no scope named ${name} in ${rel}`, stamp()];
    if (cands.length > 1)
      return [
        `pick one scope of ${rel}: ${cands.map(x => `${x.kind} ${x.name} (line ${x.line})`).join(' · ')} — a waiver names exactly one, and \`${name}\` here names ${cands.length}`,
        stamp(),
      ];
    const createdAt = new Date().toISOString().slice(0, 10);
    const author = opts.author || process.env.USER || '';
    const id = createHash('sha256')
      .update(['waiver', rel, name, pid, author, createdAt].join('|'))
      .digest('hex')
      .slice(0, 8);
    if (readSeeds(store).waivers.some(wv => wv.id === id))
      return [
        `waiver ${id} already exists for ${rel}#${name} on ${pid} — \`grain decide rm ${id}\` first to change it`,
        stamp(),
      ];
    mkdirSync(store.base, { recursive: true });
    ensureSeedAttrs(store);
    appendFileSync(
      store.seedsPath,
      JSON.stringify({ id, waiver: { path: rel, name, pid }, note: opts.note || '', author, createdAt }) +
        '\n'
    );
    appendDecision(store, { action: 'add', id, at: createdAt, by: author, note: opts.note || '' });
    return [
      `recorded waiver ${id} in .grain/seeds.jsonl — ${rel}#${name} (line ${cands[0].line}) is excused from ${pid}. \`check\` will say the departure is deliberate instead of flagging it; the counts still report it as non-conforming. Commit .grain/seeds.jsonl and .grain/decisions.jsonl.`,
      stamp(),
    ];
  }
  if (sub === 'add-boundary') {
    const from = args[1];
    const to = opts['never-imports'];
    if (!from || !to)
      throw new Error(
        'usage: grain seed add-boundary <fromDir> --never-imports <toDir> --note "…" [--author X]'
      );
    const fromDir = String(from).replace(/\/$/, ''),
      toDir = String(to).replace(/\/$/, '');
    const createdAt = new Date().toISOString().slice(0, 10);
    const author = opts.author || process.env.USER || '';
    const id = createHash('sha256')
      .update(['boundary', fromDir, toDir, author, createdAt].join('|'))
      .digest('hex')
      .slice(0, 8);
    if (readSeeds(store).boundaries.some(bd => bd.id === id))
      return [`boundary ${id} already exists — \`grain seed rm ${id}\` first to change it`, stamp()];
    const mg = model.moduleGraph;
    const existing = (mg?.edges || []).filter(
      e => (e.from + '/').startsWith(fromDir + '/') && (e.to + '/').startsWith(toDir + '/')
    );
    mkdirSync(store.base, { recursive: true });
    ensureSeedAttrs(store);
    appendFileSync(
      store.seedsPath,
      JSON.stringify({
        id,
        boundary: { from: fromDir, to: toDir },
        note: opts.note || '',
        author,
        createdAt,
      }) + '\n'
    );
    appendDecision(store, { action: 'add-boundary', id, at: createdAt, by: author, note: opts.note || '' });
    return [
      `recorded boundary ${id} in .grain/seeds.jsonl — ${fromDir}/ never imports ${toDir}/. ${
        existing.length
          ? `NOTE: the graph already holds ${existing.length} module edge(s) crossing it (${existing
              .slice(0, 3)
              .map(e => `${e.from}→${e.to} ×${e.n}`)
              .join(' · ')}) — existing code is a transition, new code will be flagged by \`check\`.`
          : 'No existing edges cross it.'
      } Commit .grain/seeds.jsonl and .grain/decisions.jsonl.`,
      stamp(),
    ];
  }
  throw new Error(
    'usage: grain decide steer|boundary|waive|list|rm … (grain seed add|add-boundary|list|rm is the same command)'
  );
}
