// grain CLI — the query surface over the engine, with the index store, auto-refresh and freshness stamps.
//
//   grain where <intent words>      intent → where such things live, what is expected there, exemplars, co-change
//   grain check <file>              how this file (its WORKTREE version) sits against the local norm field
//   grain review                    one aggregated report over every file in your whole uncommitted change
//   grain spectrum <file>           the full local→global convention lattice for one file, no acceptance cut
//   grain status | grain report     model overview, freshness, trends, health
//   grain refresh [--full]          rebuild the index now (auto-refresh already runs before every query)
//
// Every answer ends with `as of <sha>[+dirty]`. The index lives in <repo>/.grain/cache/ (gitignored, disposable).
// Uncommitted changes never feed the norm — only `check`/`review`/`spectrum` read the worktree version of the file(s) asked about.
import { existsSync, mkdirSync, readFileSync, renameSync, statSync, writeFileSync, readdirSync, appendFileSync, realpathSync } from 'node:fs';
import { join, relative, resolve, isAbsolute, dirname, extname, basename, dirname as pdirname } from 'node:path';
import { dirname as posixDirname } from 'node:path/posix'; // matches placementHit's own dirname(rel) in core.mjs — `rel` is toPosix'd, so this is the correct dirname, not node:path's platform-dependent one
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { ENGINE_VERSION, EXTR_V, MODEL_V, GRAMMAR_DIR, GRAMMARS, EXCL, EXT2GRAMMAR, HARD_EXCL } from './config.mjs';
import { learn, checkFile, spectrum, whereCmd, report, rulesMarkdown, statusLines, completenessDirectional, mutateTest, walkFiles, verbalize, toPosix, scopeLabel, groupDeviations, factLabel, placementHit, sufOf, nameTokens, fileLevelPreds, pct, scopeLine, part } from './core.mjs';
import { loadHistory, headSha, headTree, gitOk, isShallow } from './history.mjs';
import { exportModel } from './export.mjs';
import { createHash } from 'node:crypto';
import { hydrateScope, applyVocab, partitionFor, verbalize as verb2, baselineShare } from './core.mjs';

const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BIN = join(PLUGIN_ROOT, 'bin', 'grain.mjs');

// ----- argv -----
export function parseArgv(argv) {
  const opts = {}; const args = [];
  for (let i = 0; i < argv.length; i++) { const a = argv[i];
    if (a === '--') { args.push(...argv.slice(i + 1)); break; }
    if (a.startsWith('--')) { const [k, ...v] = a.slice(2).split('='); if (v.length) opts[k] = v.join('='); else if (['repo', 'top', 'minbits', 'as', 'content', 'mode', 'map-rows', 'out', 'max-sites', 'surfaces', 'instead-of', 'never-imports', 'weight', 'topic', 'note', 'author', 'range'].includes(k) && argv[i + 1] !== undefined && !argv[i + 1].startsWith('--')) opts[k] = argv[++i]; else opts[k] = true; }
    else args.push(a); }
  return { cmd: args[0], args: args.slice(1), opts }; }

// ----- repo + store -----
export function findRoot(opts) {
  const start = resolve(opts.repo || process.cwd());
  if (opts.repo && !existsSync(start)) throw new Error(`no such directory: ${start}`);
  try { return { root: execFileSync('git', ['-C', start, 'rev-parse', '--show-toplevel'], { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(), git: true }; }
  catch { return { root: start, git: false }; } }
// Two stores under <repo>/.grain/ (the spec's store triad minus local state, which a query tool does not keep):
//   .grain/cache/   rebuildable, gitignored — model.json, meta.json, history.json, blobs/   (safe to wipe: `rm -rf .grain/cache`)
//   .grain/         committed inputs — reserved for maintainer seeds (seeds.jsonl) and their audit trail (decisions.jsonl)
// .grain/.gitignore ignores `cache/`, so nothing generated can be committed even when the user never touches the root .gitignore.
export function storeFor(root) { const base = join(root, '.grain'); const dir = join(base, 'cache');
  return { base, dir, modelPath: join(dir, 'model.json'), metaPath: join(dir, 'meta.json'), historyPath: join(dir, 'history.json'), blobsDir: join(dir, 'blobs'), scopesPath: join(dir, 'scopes.json'), treePath: join(dir, 'tree.json'), seedsPath: join(base, 'seeds.jsonl') }; }
function ensureStore(root, store) {
  mkdirSync(store.dir, { recursive: true });
  const gi = join(store.base, '.gitignore');
  if (!existsSync(gi)) { writeFileSync(gi, '# generated by grain — the cache is disposable; everything else in .grain/ is meant to be committed\ncache/\n'); console.error('[grain] created .grain/.gitignore (ignores .grain/cache/)'); } }
const atomicWrite = (p, d) => { const t = p + '.tmp-' + process.pid; writeFileSync(t, d); renameSync(t, p); };
const readJson = p => { try { return JSON.parse(readFileSync(p, 'utf8')); } catch { return null; } };
const grammarStamp = () => { const m = readJson(join(GRAMMAR_DIR, 'manifest.json')); return m ? Object.entries(m).map(([g, v]) => g + '@' + v.version).join(',') : GRAMMARS.join(','); };
// cheap signature of the tree for repositories without git: (path,size,mtime) of every code file
function treeSig(root) { let h = 2166136261; const mix = s => { for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } };
  for (const rel of [...walkFiles(root, root)].sort()) { try { const st = statSync(join(root, rel)); mix(rel + ':' + st.size + ':' + st.mtimeMs); } catch {} }
  return (h >>> 0).toString(16); }

export const short = sha => sha ? sha.slice(0, 7) : 'no-git';
const log = (...a) => console.error('[grain]', ...a);

/**
 * Freshness protocol (runs before every query):
 *   same HEAD as indexed → answer immediately; new commits on the same line → incremental update, then answer;
 *   divergent history → full rebuild on the warm blob cache (or, with --no-refresh, answer with a STALE banner);
 *   no index → build. Worktree edits never trigger a rebuild (the norm is the accepted past — by design).
 */
export async function ensureFresh({ root, isGit, store, opts, want = 'refresh' }) {
  const head = isGit ? headSha(root) : null;
  const meta = readJson(store.metaPath); const model = existsSync(store.modelPath) ? readJson(store.modelPath) : null;
  const versionOk = meta && meta.engine === ENGINE_VERSION && meta.extractor === EXTR_V && (meta.model || '') === MODEL_V && meta.grammars === grammarStamp();
  const { seeds, boundaries } = readSeeds(store); const seedsHash = hashSeeds({ seeds, boundaries });
  const sig = isGit ? null : treeSig(root);
  const cachedWithHistory = meta && meta.historyMode && meta.historyMode !== 'none';
  const cachedNoHistoryByFlag = meta && meta.historyMode === 'none' && meta.historyReason === '--no-history flag';
  const cachedShallow = meta && meta.historyReason === 'shallow clone — history unavailable, weights flat';
  const nowUnshallow = cachedShallow && isGit && !isShallow(root); // §G13: the cache says shallow, but the repo isn't anymore — that alone must invalidate freshness, even though headSha/version/seeds all still match
  const fresh = model && versionOk && (meta.seedsHash || '') === seedsHash && (isGit ? meta.headSha === head : meta.treeSig === sig) // a changed seeds file re-mines like a new commit would
    && !(cachedNoHistoryByFlag && !opts['no-history']) // §G12 (symmetric case): a cache built under --no-history must not silently serve a no-flag call as if it had full history — force a real rebuild instead
    && !nowUnshallow;
  const banner = [];
  if (fresh && want !== 'force') {
    if (opts['no-history'] && cachedWithHistory) { // §G12: a per-invocation --no-history must not be silently ignored by an otherwise-fresh WITH-history cache
      const treeCache = readJson(store.treePath);
      const tree = isGit && head ? headTree(root, { skip: (rel, sha) => !!(treeCache && treeCache[sha + '|' + rel]) }) : null;
      const { model: m2 } = await learn({ root, H: null, log, tree, treeCache, seeds, boundaries });
      return { model: m2, meta: { ...meta, historyMode: 'none', historyReason: '--no-history flag' }, head, banner }; } // in-memory only — the persisted store is NEVER touched here, the flag is per-invocation, not a change to indexed state
    return { model, meta, head, banner }; }
  if (want === 'none') { // caller refuses to rebuild (hook path, or --no-refresh): answer stale, never silently
    if (!model) return { model: null, meta, head, banner: ['NO INDEX: run `grain refresh` (or any query) to build it'] };
    banner.push(`STALE: indexed at ${short(meta?.headSha)}, HEAD is ${short(head)}${versionOk ? '' : ' (engine/grammar version changed)'} — run \`grain refresh\``);
    return { model, meta, head, banner, stale: true }; }
  ensureStore(root, store);
  const t0 = Date.now();
  let H = null, hist = { mode: 'none', reason: isGit ? '--no-history flag' : 'not a git repository (or no commits yet)' };
  if (isGit && !opts['no-history']) { hist = await loadHistory({ gitdir: root, store, log, full: want === 'force' && !!opts.full || !versionOk }); H = hist.H;
    if (hist.mode === 'none') log(`history: ${hist.reason}`); }
  log(`indexing ${root} (${hist.mode === 'incremental' ? 'incremental' : hist.mode === 'unchanged' ? 'history unchanged' : hist.mode === 'full' ? 'full history' : 'no history'})`);
  const treeCache = versionOk ? readJson(store.treePath) : null; // (blob sha, path) → extracted scopes, from the previous index
  const tree = isGit && head ? headTree(root, { skip: (rel, sha) => !!(treeCache && treeCache[sha + '|' + rel]) }) : null;
  const { model: m2, ms, scopes, rawScopes, treeCacheOut } = await learn({ root, H, log, tree, treeCache, seeds, boundaries });
  atomicWrite(store.modelPath, JSON.stringify(m2));
  if (tree) atomicWrite(store.treePath, JSON.stringify(treeCacheOut)); else atomicWrite(store.scopesPath, JSON.stringify(rawScopes));
  const meta2 = { engine: ENGINE_VERSION, extractor: EXTR_V, model: MODEL_V, grammars: grammarStamp(), headSha: head, treeSig: sig, seedsHash, historyMode: hist.mode, historyReason: hist.reason || null,
    builtAt: new Date().toISOString(), buildMs: Date.now() - t0, scopes };
  atomicWrite(store.metaPath, JSON.stringify(meta2, null, 1));
  log(`indexed in ${((Date.now() - t0) / 1000).toFixed(1)}s: ${m2.partitions.reduce((a, p) => a + p.facts.length, 0)} conventions, ${scopes} scopes, learn ${ms}ms`);
  return { model: m2, meta: meta2, head, banner }; }

// exemplar re-validation at render time is a memoized existence check (never a re-parse)
const existsMemo = root => { const m = new Map(); return rel => { if (!m.has(rel)) m.set(rel, existsSync(join(root, rel))); return m.get(rel); }; };
// worktree vs HEAD for one file: dirty ⇔ untracked, or content differs from the HEAD blob
function fileDirty(root, rel, isGit, diffArgs) { if (!isGit) return true;
  if (!diffArgs && !gitOk(root, ['ls-files', '--error-unmatch', '--', rel])) return true;
  return !gitOk(root, ['diff', '--quiet', ...(diffArgs || ['HEAD']), '--', rel]); }
// the worktree lines this file changed against HEAD (untracked ⇒ every line; clean ⇒ none): `check` reports deviations in
// the caller's own change first and folds pre-existing ones into a count — measured: 11 pre-existing deviations and 0 about
// the change on one flask file was 1.5k tokens of noise
function changedRanges(root, rel, isGit, diffArgs) { if (!isGit) return null;
  if (!diffArgs && !gitOk(root, ['ls-files', '--error-unmatch', '--', rel])) return [[1, Infinity]];
  let out; try { out = execFileSync('git', ['-C', root, 'diff', '-U0', ...(diffArgs || ['HEAD']), '--', rel], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }); } catch { return null; }
  const ranges = []; for (const m of out.matchAll(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@/gm)) { const a = +m[1], n = m[2] === undefined ? 1 : +m[2]; ranges.push(n === 0 ? [a, a + 1] : [a, a + n - 1]); } // a pure deletion touches the line after its point (the class whose decorator was deleted)
  return ranges; }
function canonicalize(p) { // realpath through the deepest EXISTING ancestor — handles a path not yet on disk (a
  // pre-write path) and OS symlinks (macOS /tmp -> /private/tmp) that would otherwise put a valid path "outside"
  // its own repository; shared by relPath and check-hook's PreToolUse path resolution
  try { return realpathSync(p); } catch {
    let d2 = p; const tail = []; while (!existsSync(d2)) { tail.unshift(basename(d2)); const nd = pdirname(d2); if (nd === d2) break; d2 = nd; }
    try { return join(realpathSync(d2), ...tail); } catch { return p; } } }
function relPath(root, p) {
  let abs;
  if (isAbsolute(p)) abs = canonicalize(p);
  else { const underRoot = resolve(root, p), underCwd = resolve(process.cwd(), p);
    abs = existsSync(underRoot) ? underRoot
      : (existsSync(underCwd) && !relative(root, underCwd).startsWith('..')) ? underCwd
      : underRoot; } // neither exists (or the cwd match would itself escape root): fall back to root-relative so a
      // distinct "no such file" check downstream catches it, not a false "outside"
  const rel = toPosix(relative(root, abs));
  if (rel.startsWith('..')) throw new Error(`${p} is outside the repository ${root}`); return rel; }

// ----- commands -----
export async function cmdWhere({ model, root, args, opts, stamp }) {
  if (!args.length) throw new Error('usage: grain where <intent words>');
  const { lines } = whereCmd({ model, query: args.join(' '), top: +opts.top || 3, mapRows: +opts['map-rows'] || 60, exemplarOk: existsMemo(root) });
  const sig = signal(model); if (/empty|sparse|no source/.test(sig.verdict)) lines.push(`model note: ${sig.facts} conventions over ${sig.files} source files — ${sig.verdict}`);
  if (opts.json) { const { hits } = whereCmd({ model, query: args.join(' '), top: +opts.top || 3, mapRows: +opts['map-rows'] || 60, exemplarOk: existsMemo(root) });
    return [JSON.stringify({ query: args.join(' '), hits: hits.map(h => ({ type: h.type, label: h.label, partition: h.part, score: +h.score.toFixed(3), size: h.n, directories: h.topDirs.map(([d, n]) => ({ dir: d, n })),
      // a `file` card's own keys already bake in the real line as their 4th segment (`rel#kind#name#line`, built
      // in core.mjs's card-building pass) — unlike every other card type, whose keys are `skeyR` identity keys
      // (`rel#kind#name[#ord]`) where a 4th segment, when present, is a dedup ordinal, never a line. Matches the
      // text-rendering path's own split: `h.type === 'file'` naively destructures the key (core.mjs's `matching`),
      // every other type resolves through `scopeLine` (core.mjs's `withLine`).
      members: h.members ? h.members.slice(0, 12).map(k => { const [rel, kind, name, rawLine] = k.split('#');
        return { rel, kind, name, line: h.type === 'file' ? (rawLine ? +rawLine : null) : scopeLine(part(model, h.part), k) }; }) : undefined,
      conventions: h.facts.slice(0, 6).map(f => ({ id: h.part + '::' + f.cid + '::' + f.pid, statement: verbalize(f, f.exemplars.map(e => e.name)), share: f.share, established: f.sraw, exemplars: f.exemplars, deviants: f.deviants || [], trend: f.trend ? f.trend.shares.map(x => x.share) : null, held: f.held || null })) })),
      signal: sig, asOf: stamp().replace(/^as of /, '') })]; }
  return [...lines, stamp()]; }
// per-scope conformance tally from a checkFile() result — shared by `check` (its own "conforms to:" line) and
// `review`'s --json (the same `governed` shape, per file)
function govFactsOf(r) { const m = new Map();
  for (const g of r.governed) { const k = g.fact.cid + '|' + g.pid; const e = m.get(k) || { g, n: 0, ok: 0 }; e.n++; if (g.conforms) e.ok++; m.set(k, e); }
  return m; }
// the core "turn one checkFile() result into THIS file's own finding lines" step — shared by `check` (one file, full
// detail: this feeds its in-change/pre-existing split, everything else in cmdCheck is check-only presentation) and
// `review` (many files: only these four categories count as a finding — placement, maintainer decisions departed
// from, architecture hits, and deviations inside the lines this file itself changed; pre-existing deviations outside
// the change are deliberately excluded here too, same "not yours to fix" discipline as single-file `check`)
async function fileFindings({ root, rel, isGit, dirty, r, wholeFile = false, diffArgs }) {
  const ranges = wholeFile ? [[1, Infinity]] : (dirty ? changedRanges(root, rel, isGit, diffArgs) : []);
  const touched = ranges === null ? null : ((from, to) => ranges.some(([a, b]) => to >= a && from - 3 <= b)); // a scope is "in your change" when any changed line falls inside it or in the three lines above it (its decorator stack)
  // a file-kind fact (quote style, filename shape, export style…) describes the WHOLE file's content, not a bounded
  // line range — its pseudo-scope sits at line 1 (extractScopes, core.mjs), so the line-range `touched` above would
  // misattribute it by whether the diff happens to touch line 1, not by whether THIS edit changed the fact's value
  // (G10). Classify it instead by comparing against the predicate recomputed on the file's content at the correct
  // "before" ref — one extra parse, only when a file-kind deviation actually exists and the file is dirty.
  let fkTouched = null;
  if (!wholeFile && dirty && r.msgs.some(m => m.kind === 'file')) {
    const beforeRef = (diffArgs && diffArgs.length === 2) ? diffArgs[0] : 'HEAD'; // --range a..b compares against a; default/--worktree/--staged all compare against HEAD (--cached's own baseline)
    const headSrc = refContent(root, beforeRef, rel);
    if (headSrc == null) fkTouched = () => true; // untracked, or didn't exist at beforeRef — every file-kind deviation is "in your change" by construction
    else { const headPreds = await fileLevelPreds(rel, headSrc); fkTouched = m => headPreds[m.pid] !== m.obs; } }
  const grouped = groupDeviations(r.msgs, touched, fkTouched);
  const inChange = grouped.filter(g => g.touched), preOnly = grouped.filter(g => !g.touched);
  const steerIn = (r.steerHits || []).filter(h => !touched || touched(h.line, h.endLine)), steerPre = (r.steerHits || []).filter(h => touched && !touched(h.line, h.endLine));
  const archIn = (r.archHits || []).filter(h => !touched || touched(h.line, h.line)), archPre = (r.archHits || []).filter(h => touched && !touched(h.line, h.line));
  const lines = [...steerIn.map(h => h.text), ...(r.placeHit ? [r.placeHit.text] : []), ...archIn.map(h => h.text), ...inChange.map(g => g.text + `\n  (preference gap ${g.delta} bits)`)];
  return { touched, grouped, inChange, preOnly, steerIn, steerPre, archIn, archPre, lines }; }
// the machine-readable per-file verdict — the exact shape `check --json` has always returned, reused as-is for one
// file inside `review --json` so the two never drift into two schemas for the same facts
function fileVerdictJson({ rel, r, dirty, f, govFacts, stamp }) {
  const scopesN = r.scopes.filter(s => s.kind !== 'file').length;
  const { touched, inChange, preOnly } = f;
  const dev = g => ({ convention: r.partition + '::' + g.factKey.split('|')[0] + '::' + g.pid, label: g.label, pid: g.pid, expected: g.exp, observed: g.obs, gapBits: g.delta,
    statement: g.text.split('\n')[0].replace(/^\[grain\] /, ''), hits: g.hits.map(h => ({ scope: h.scope, kind: h.kind, line: h.line, inChange: h.touched })) });
  return { file: rel, partition: r.partition, label: r.partition ? scopeLabel(r.partition) : null, scopes: scopesN, dirty, hasError: !!r.hasError,
    governed: [...govFacts.values()].map(e => ({ convention: r.partition + '::' + e.g.fact.cid + '::' + e.g.pid, label: e.g.label, statement: verbalize(e.g.fact, e.g.fact.exemplars.map(x => x.name)), established: e.g.fact.sraw, share: e.g.fact.share, scopes: e.n, conforming: e.ok })),
    deviationsInChange: inChange.map(dev), deviationsPreExisting: preOnly.map(dev),
    steers: (r.steerHits || []).map(h => ({ seed: h.id, pid: h.pid, expected: h.exp, observed: h.obs, scope: h.scope, kind: h.kind, line: h.line, inChange: !touched || touched(h.line, h.endLine) })),
    architecture: (r.archHits || []).map(h => ({ kind: h.kind, to: h.to, line: h.line, seed: h.id || null, inChange: !touched || touched(h.line, h.line) })),
    placement: r.placeHit ? { token: r.placeHit.token, dir: r.placeHit.dir, statement: r.placeHit.text.replace(/^\[grain\] /, '') } : null,
    asOf: stamp(dirty).replace(/^as of /, '') }; }
export async function cmdCheck({ model, root, isGit, args, opts, stamp }) {
  if (!args[0]) throw new Error('usage: grain check <file> [--as <repo-relative path>]');
  const rel = relPath(root, args[0]); const content = opts.content ? readFileSync(opts.content, 'utf8') : undefined;
  if (!content && !existsSync(join(root, rel))) throw new Error(`no such file: ${rel}`);
  if (!EXT2GRAMMAR[extname(rel)]) { const ph = placementHit(model, rel); const dirty0 = fileDirty(root, rel, isGit);
    if (opts.json) return [JSON.stringify({ file: rel, noGrammar: extname(rel) || null, dirty: dirty0, placement: ph ? { token: ph.token, dir: ph.dir, statement: ph.text.replace(/^\[grain\] /, '') } : null, asOf: stamp(dirty0).replace(/^as of /, '') })];
    return [`check ${rel}: no grammar for "${extname(rel) || 'a file without extension'}" — grain parses ${GRAMMARS.join(', ')}`, ...(ph ? [ph.text] : []), stamp(dirty0)]; }
  const r = await checkFile({ model, root, rel, content, asPath: opts.as, exemplarOk: existsMemo(root) });
  const dirty = content ? true : fileDirty(root, rel, isGit);
  const lines = [];
  if (!r.partition) { const arch = (r.archHits || []).map(h => h.text);
    if (opts.json) return [JSON.stringify({ file: rel, noPartition: true, reason: r.reason, placement: r.placeHit ? { token: r.placeHit.token, dir: r.placeHit.dir, statement: r.placeHit.text.replace(/^\[grain\] /, '') } : null, architecture: (r.archHits || []).map(h => ({ kind: h.kind, to: h.to, line: h.line, seed: h.id || null })), asOf: stamp(dirty).replace(/^as of /, '') })];
    return [`check ${rel}: ${r.reason} — grain has no norm to hold this file against`, ...(r.placeHit ? [r.placeHit.text] : []), ...arch, stamp(dirty)]; }
  const scopesN = r.scopes.filter(s => s.kind !== 'file').length;
  if (r.hasError && scopesN === 0) { // a real parse failure, not a genuinely trivial file — the ONLY case this branch may fire for now (it used to be permanently dead: r.scopes.length is never 0 because extractScopes always pushes a file-kind pseudo-scope)
    if (opts.json) return [JSON.stringify({ file: rel, parseFailed: true, hasError: true, asOf: stamp(dirty).replace(/^as of /, '') })];
    return [`check ${rel}: parse failed — this file is largely unparseable (unsupported syntax or a grammar limitation); its scope list is empty and may be missing real content`, stamp(dirty)]; }
  const govFacts = govFactsOf(r);
  const { touched, inChange, preOnly, steerIn, steerPre, archIn, archPre } = await fileFindings({ root, rel, isGit, dirty, r, wholeFile: !!content });
  if (opts.json) return [JSON.stringify(fileVerdictJson({ rel, r, dirty, f: { touched, inChange, preOnly }, govFacts, stamp }))]; // machine-readable verdict: the same facts `check` prints, as data (consumers: harnesses, training pipelines)
  lines.push(`check ${rel} — ${scopeLabel(r.partition)} · ${scopesN} scopes + file · governed by ${govFacts.size} convention(s) · ${inChange.length} deviation(s) in your change, ${preOnly.length} pre-existing${steerIn.length ? ` · ${steerIn.length} maintainer decision(s) your change departs from` : ''}`);
  if (r.hasError) lines.push(`  (parse degraded — part of this file sits in error nodes; the scope list above may be incomplete)`);
  if (steerPre.length && !steerIn.length) lines.push(`  (${steerPre.length} existing ${steerPre.length > 1 ? 'scopes are' : 'scope is'} still on a pattern a maintainer decision retires — a transition in progress, not yours to fix; \`--all\` lists)`);
  for (const h of steerIn) lines.push(h.text);
  if (r.placeHit) lines.push(r.placeHit.text);
  for (const h of archIn) lines.push(h.text);
  if (archPre.length) lines.push(`  (${archPre.length} architecture note(s) on lines you did not touch — \`--all\` shows${opts.all ? ':' : ''})`);
  if (archPre.length && opts.all) for (const h of archPre) lines.push(h.text);
  if (steerPre.length && steerIn.length) lines.push(`  (${steerPre.length} more existing ${steerPre.length > 1 ? 'scopes' : 'scope'} still on the retired pattern — a transition in progress, not yours to fix)`);
  if (steerPre.length && opts.all) for (const h of steerPre) lines.push(h.text);
  // superficial: a file-level fact by definition, or a naming-shape/lexical surface — governs no behavior even when it
  // sits on a type/method-kind scope (a class named PascalCase is not a "shape of code" certification any more than a
  // file's import style is)
  const SUPERFICIAL_PID = /^auto\.(nameshape|filenameshape)$|^auto\.lex:/;
  if (!govFacts.size) lines.push('  no strong convention governs this file — grain has nothing certified for this kind of file here; that is not approval, open the nearest neighbour and copy it');
  else if ([...govFacts.values()].every(e => e.g.fact.kind === 'file' || SUPERFICIAL_PID.test(e.g.fact.pid))) lines.push('  only naming and lexical style is certified here (quotes, declarations, imports, name shape) — nothing about the shape of this file\'s code; that is not approval, open the nearest neighbour and copy it');
  for (const g of inChange) lines.push(g.text + `\n  (preference gap ${g.delta} bits)`);
  if (preOnly.length) { if (opts.all) for (const g of preOnly) lines.push(g.text + `\n  (preference gap ${g.delta} bits)`);
    else lines.push(`pre-existing (not in your change, not yours to fix — \`--all\` to list): ${preOnly.slice(0, 4).map(g => `${g.label}: ${verbalize({ ...g, kind: g.kind }, g.exNames || []).replace(/ here /, ' ')} ×${g.pre}`).join(' · ')}${preOnly.length > 4 ? ` · +${preOnly.length - 4} more` : ''}`); }
  const ok = [...govFacts.values()].filter(e => e.ok === e.n && !(e.g.fact.exp === 'false' && /^auto\.(has|call|deco|extends|imp|stshape|returns):/.test(e.g.pid)));
  const supNote = e => e.g.fact.contested ? ` — superseded by maintainer decision ${e.g.fact.contested}` : '';
  if (ok.length) lines.push(`conforms to: ${ok.slice(0, 6).map(e => `${e.g.label}: ${verbalize(e.g.fact, e.g.fact.exemplars.map(x => x.name))} (${pct(e.g.fact.share)}% of ${e.g.fact.sraw})${supNote(e)}`).join(' · ')}${ok.length > 6 ? ` · +${ok.length - 6} more` : ''}`);
  lines.push(stamp(dirty)); return lines; }
// plain git plumbing, no new wrapper (mirrors changedRanges/fileDirty above): `git diff --name-only <ref-args>` for
// --staged and --range; default/--worktree unions the worktree-vs-HEAD diff (covers staged AND unstaged, since a
// plain `diff HEAD` already compares the full working tree to HEAD regardless of the index) with untracked new
// files, because an agent mid-task has usually not staged anything yet. A bad --range is not our error to shape —
// stderr is captured and re-thrown verbatim so git's own message reaches the user.
function gitNameOnly(root, args) {
  let out; try { out = execFileSync('git', ['-C', root, ...args, '-z'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); }
  catch (e) { throw new Error((e.stderr || e.message || '').toString().trim() || `git ${args.join(' ')} failed`); }
  return out.split('\0').filter(Boolean); }
function reviewFileList(root, opts) {
  const raw = opts.range ? gitNameOnly(root, ['diff', '--name-only', opts.range])
    : opts.staged ? gitNameOnly(root, ['diff', '--cached', '--name-only'])
    : [...gitNameOnly(root, ['diff', '--name-only', 'HEAD']), ...gitNameOnly(root, ['ls-files', '--others', '--exclude-standard'])];
  return [...new Set(raw.map(toPosix))].filter(p => !HARD_EXCL.test(p)).sort(); } // sorted for a deterministic, reviewable report — git's own diff order is an artifact of its tree walk, not signal
// which git refs define "the change" for this review mode, and where to read a file's content from — null means
// the existing worktree-vs-HEAD behavior (default/--worktree), unchanged
function reviewRefs(opts) {
  if (opts.range) { const m = /^(.+?)\.{2,3}(.+)$/.exec(opts.range);
    if (!m) throw new Error(`--range must be <a>..<b>, got "${opts.range}"`);
    return { diffArgs: [m[1], m[2]], contentRef: m[2] }; } // review the file AS OF the range's end commit, so line numbers in the diff match the content being parsed
  if (opts.staged) return { diffArgs: ['--cached'], contentRef: '' }; // '' + ':' + rel => git's `:rel` syntax for the index/staged blob
  return null; }
function refContent(root, ref, rel) {
  try { return execFileSync('git', ['-C', root, 'show', `${ref}:${rel}`], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }); }
  catch { return null; } } // deleted at that ref / not tracked there — nothing to check
async function cmdReview({ model, root, isGit, args, opts, stamp }) {
  if (!isGit) return ['review: not a git repository — there is no committed HEAD to measure "your change" against', stamp()];
  const files = reviewFileList(root, opts); // throws with git's own stderr on a bad --range
  const refs = reviewRefs(opts); // null | { diffArgs, contentRef } — see reviewRefs
  let anyDirty = false; const perFile = [];
  for (const rel of files) {
    const dirty = fileDirty(root, rel, isGit, refs?.diffArgs); anyDirty = anyDirty || (!opts.range && dirty); // "+dirty" in the stamp means "used uncommitted content" — never true for an already-committed --range
    const content = refs ? refContent(root, refs.contentRef, rel) : undefined;
    if (refs ? content == null : !existsSync(join(root, rel))) continue; // deleted at the ref / deleted in worktree — nothing left to hold against a norm
    if (!EXT2GRAMMAR[extname(rel)]) { const ph = placementHit(model, rel); // no grammar: only a placement signal can still speak (mirrors `check`'s no-grammar case)
      if (ph) perFile.push({ rel, dirty, r: null, f: { steerIn: [], archIn: [], inChange: [], preOnly: [], lines: [ph.text] } });
      continue; }
    let r; try { r = await checkFile({ model, root, rel, content, exemplarOk: existsMemo(root) }); }
    catch (e) { perFile.push({ rel, dirty, r: null, f: { steerIn: [], archIn: [], inChange: [], preOnly: [], lines: [`[grain] ${rel}: parse failed — skipped (${e.message})`] } }); continue; }
    const f = await fileFindings({ root, rel, isGit, dirty, r, diffArgs: refs?.diffArgs });
    if (!f.lines.length) continue; // no finding at all — contributes nothing, not even a placeholder
    perFile.push({ rel, dirty, r, f }); }
  // presentation order, not a mathematically constrained gate: maintainer-decision/architecture hits first (the
  // highest-stakes findings), then plain deviations ranked by how many and how strong, placement-only files last
  const rank = e => (e.f.steerIn.length || e.f.archIn.length) ? [0, -(e.f.steerIn.length + e.f.archIn.length), -e.f.inChange.length]
    : e.f.inChange.length ? [1, -e.f.inChange.length, -e.f.inChange.reduce((a, g) => a + g.delta, 0)] : [2, 0, 0];
  perFile.sort((a, b) => { const ra = rank(a), rb = rank(b); for (let i = 0; i < ra.length; i++) if (ra[i] !== rb[i]) return ra[i] - rb[i]; return a.rel < b.rel ? -1 : 1; });
  const totalFindings = perFile.reduce((a, e) => a + e.f.lines.length, 0);
  const cc = completenessDirectional(model, files); // the WHOLE set's missing co-change partners, not per-file
  const ccPartners = cc.length > 1 ? cc.slice(1) : []; // the "(complete — …)" placeholder makes sense answering one direct query; in an aggregated report most reviews have no hit, so it would be noise repeated on every clean run — say nothing instead
  if (opts.json) return [JSON.stringify({ files,
    findings: perFile.map(e => e.r ? fileVerdictJson({ rel: e.rel, r: e.r, dirty: e.dirty, f: e.f, govFacts: govFactsOf(e.r), stamp })
      : { file: e.rel, noGrammar: extname(e.rel) || null, dirty: e.dirty, placement: { statement: e.f.lines[0].replace(/^\[grain\] /, '') } }),
    cochangePartners: ccPartners.map(x => x.replace(/^\s*-\s*/, '')), asOf: stamp(anyDirty).replace(/^as of /, '') })];
  const lines = [`review ${files.length} file${files.length === 1 ? '' : 's'} · ${totalFindings} finding(s) across ${perFile.length} file(s)`];
  if (!totalFindings && !ccPartners.length) lines.push(`clean — nothing to report across ${files.length} file${files.length === 1 ? '' : 's'} reviewed`);
  for (const e of perFile) { lines.push(`== ${e.rel} — ${e.f.lines.length} finding(s) ==`); for (const l of e.f.lines) lines.push(l); }
  if (ccPartners.length) lines.push(cc[0], ...ccPartners);
  lines.push(stamp(anyDirty)); return lines; }
async function cmdSpectrum({ model, root, isGit, args, opts, stamp, store }) {
  if (!args[0]) throw new Error('usage: grain spectrum <file> [--minbits N] [--top N]');
  const rel = relPath(root, args[0]);
  const treeCache = readJson(store.treePath); // (sha|path) → { s: scopes, r: relation facts } of HEAD's files
  const scopesAll = treeCache ? Object.values(treeCache).flatMap(v => Array.isArray(v) ? v : v.s) : readJson(store.scopesPath);
  const r = await spectrum({ model, root, rel, minBits: opts.minbits !== undefined ? +opts.minbits : 0, top: +opts.top || 0, scopesAll });
  return [...r.lines, stamp(fileDirty(root, rel, isGit))]; }
// ----- seeds (steering): .grain/seeds.jsonl, committed; one maintainer decision per line -----
function readSeeds(store) { const out = []; const boundaries = [];
  if (existsSync(store.seedsPath)) for (const line of readFileSync(store.seedsPath, 'utf8').split('\n')) { const t = line.trim(); if (!t || t.startsWith('#')) continue;
    try { const j = JSON.parse(t);
      if (j && j.boundary && j.boundary.from && j.boundary.to) boundaries.push({ id: j.id, boundary: { from: j.boundary.from.replace(/\/$/, ''), to: j.boundary.to.replace(/\/$/, '') }, note: j.note || '', author: j.author || '', createdAt: j.createdAt || '' });
      else if (j && j.scope && j.scope.path && Array.isArray(j.surfaces) && j.surfaces.length) out.push({ id: j.id, path: j.scope.path, name: j.scope.name, pids: j.surfaces.concat(j.retired || []), retired: j.retired || [], weight: +j.weight || 8, topic: j.topic || '', note: j.note || '', author: j.author || '', createdAt: j.createdAt || '', baseline: j.baseline || null }); }
    catch { log(`seeds.jsonl: skipped an unparsable line: ${t.slice(0, 60)}`); } }
  return { seeds: out, boundaries }; }
const hashSeeds = ({ seeds, boundaries }) => (seeds.length || boundaries.length) ? createHash('sha256').update(JSON.stringify([seeds, boundaries])).digest('hex').slice(0, 16) : '';
function appendDecision(store, rec) { appendFileSync(join(store.base, 'decisions.jsonl'), JSON.stringify(rec) + '\n'); }
function ensureSeedAttrs(store) { const p = join(store.base, '.gitattributes'); if (existsSync(p)) return;
  writeFileSync(p, '# generated by grain: decisions from two branches merge line by line\nseeds.jsonl merge=union\ndecisions.jsonl merge=union\n'); log('created .grain/.gitattributes (merge=union for seeds.jsonl and decisions.jsonl)'); }
// the surfaces a scope carries right now, with values — what a maintainer picks from when recording a steer
async function scopeSurfaces({ model, store, rel, name, root, isGit, opts }) {
  const all = await loadScopes({ root, isGit, store, opts });
  const part = partitionFor(model, rel); if (!part) return { error: `no partition covers ${rel}` };
  const cands = all.filter(s => s.rel === rel && s.kind !== 'module').map(hydrateScope);
  if (!cands.length) return { error: `no scopes indexed for ${rel} (is it committed and parsed?)` };
  const s = name ? cands.find(x => x.name === name) : (cands.length === 1 ? cands[0] : null);
  if (!s) return { error: name ? `no scope named ${name} in ${rel}` : `pick one scope of ${rel}: ${cands.map(x => `${x.kind} ${x.name} (line ${x.line})`).join(' · ')}`, cands };
  applyVocab(s, part.vocab);
  const positive = Object.entries(s.preds).filter(([pid, v]) => v !== 'false' && !/^auto\.(has|stshape|dir\d|mod)/.test(pid));
  return { scope: s, surfaces: positive.map(([pid, v]) => ({ pid, value: v, statement: verb2({ pid, exp: v, kind: s.kind }, [s.name]) })) }; }
async function cmdSeed({ model, root, isGit, store, args, opts, stamp }) {
  const sub = args[0];
  if (sub === 'list') { const { seeds, boundaries } = readSeeds(store); if (!seeds.length && !boundaries.length) return ['no seeds — `grain seed add <path>#<name> --surfaces <pid,…> --note "…"` (pattern) or `grain seed add-boundary <from> --never-imports <to> --note "…"` (architecture) records a maintainer decision in .grain/seeds.jsonl', stamp()];
    return [...seeds.map(sd => `${sd.id}  ${sd.path}#${sd.name}  ${sd.pids.join(',')}  weight ${sd.weight}${sd.topic ? `  topic "${sd.topic}"` : ''}${sd.note ? `  — ${sd.note}` : ''}  (${[sd.author, sd.createdAt].filter(Boolean).join(' ')})`),
      ...boundaries.map(bd => `${bd.id}  boundary: ${bd.boundary.from}/ never imports ${bd.boundary.to}/${bd.note ? `  — ${bd.note}` : ''}  (${[bd.author, bd.createdAt].filter(Boolean).join(' ')})`), stamp()]; }
  if (sub === 'rm') { const id = args[1]; if (!id) throw new Error('usage: grain seed rm <id>');
    const lines = existsSync(store.seedsPath) ? readFileSync(store.seedsPath, 'utf8').split('\n') : []; const kept = lines.filter(l => { try { return l.trim() && JSON.parse(l).id !== id; } catch { return !!l.trim(); } });
    if (kept.length === lines.filter(l => l.trim()).length) throw new Error(`no seed with id ${id}`);
    atomicWrite(store.seedsPath, kept.join('\n') + (kept.length ? '\n' : '')); appendDecision(store, { action: 'rm', id, at: new Date().toISOString().slice(0, 10), by: opts.author || process.env.USER || '' });
    return [`removed seed ${id} — the next query re-mines without it`, stamp()]; }
  if (sub === 'add') { const target = args[1]; if (!target) throw new Error('usage: grain seed add <path>[#<scope name>] [--surfaces <pid,…>] [--instead-of <pid,…>] [--weight N] [--topic "…"] [--note "…"] [--author X]');
    const [p0, name] = target.split('#'); const rel = relPath(root, p0);
    const r = await scopeSurfaces({ model, store, rel, name, root, isGit, opts });
    if (r.error) return [r.error, stamp()];
    const want = opts.surfaces ? String(opts.surfaces).split(',').map(x => x.trim()).filter(Boolean) : [];
    const retire = opts['instead-of'] ? String(opts['instead-of']).split(',').map(x => x.trim()).filter(Boolean) : [];
    if (!want.length) return [`${rel}#${r.scope.name} (${r.scope.kind}, line ${r.scope.line}) carries these surfaces — choose which to promote and re-run with --surfaces <pid,…> (optionally --instead-of <pid,…> naming what it replaces):`, ...r.surfaces.map(x => `  ${x.pid} = ${x.value}    ${x.statement}`), '(a seed without surfaces is refused: grain will not guess which property you meant)', stamp()];
    const bad = want.filter(pid => r.scope.preds[pid] === undefined); if (bad.length) throw new Error(`${rel}#${r.scope.name} has no surface ${bad.join(', ')} — run \`grain seed add ${target}\` without --surfaces to see them`);
    // the retired surface must be one the exemplar does NOT carry (its value there is 'false'): the seed then mutes the old
    // rule wherever it fires and `check` reports carriers of the retired value as departing from the decision
    const badR = retire.filter(pid => r.scope.preds[pid] !== 'false'); if (badR.length) throw new Error(`--instead-of ${badR.join(', ')}: the exemplar ${r.scope.name} ${r.scope.preds[badR[0]] === undefined ? 'has no such surface' : 'itself carries that value'} — name a surface the exemplar has retired (its value on the exemplar is 'false')`);
    const createdAt = new Date().toISOString().slice(0, 10); const author = opts.author || process.env.USER || '';
    const id = createHash('sha256').update([rel, r.scope.name, want.concat(retire).join(','), author, createdAt].join('|')).digest('hex').slice(0, 8);
    if (readSeeds(store).seeds.some(sd => sd.id === id)) return [`seed ${id} already exists for ${rel}#${r.scope.name} on ${want.join(',')} — \`grain seed rm ${id}\` first to change it`, stamp()];
    // a creation-time snapshot of how widely the FIRST promoted surface was already practiced — read back by
    // `report`/`where` so a later reader can see whether adoption has moved since the decision was made, without
    // keeping their own notes. null when the exemplar's partition never mined a partition-wide (`_all:`) fact for
    // this (kind, pid) — a brand-new pattern, or one whose accepted convention lives only at a group/directory
    // context this snapshot deliberately does not chase (see `baselineShare` in core.mjs for the trade-off)
    const baseline = (() => { const b = baselineShare(model, rel, r.scope.kind, want[0], r.scope.preds[want[0]]); return b ? { ...b, at: createdAt } : null; })();
    const rec = { id, scope: { path: rel, name: r.scope.name }, surfaces: want, retired: retire, weight: +opts.weight || 8, topic: opts.topic || '', note: opts.note || '', author, createdAt, baseline };
    mkdirSync(store.base, { recursive: true }); ensureSeedAttrs(store);
    appendFileSync(store.seedsPath, JSON.stringify(rec) + '\n'); appendDecision(store, { action: 'add', id, at: createdAt, by: author, note: rec.note });
    return [`recorded seed ${id} in .grain/seeds.jsonl — ${want.map(pid => verb2({ pid, exp: r.scope.preds[pid], kind: r.scope.kind }, [r.scope.name])).join('; ')} (weight ${rec.weight}, capped at half the real population of each cell). Commit .grain/seeds.jsonl and .grain/decisions.jsonl; the next query re-mines with it.`, stamp()]; }
  if (sub === 'add-boundary') { const from = args[1]; const to = opts['never-imports'];
    if (!from || !to) throw new Error('usage: grain seed add-boundary <fromDir> --never-imports <toDir> --note "…" [--author X]');
    const fromDir = String(from).replace(/\/$/, ''), toDir = String(to).replace(/\/$/, '');
    const createdAt = new Date().toISOString().slice(0, 10); const author = opts.author || process.env.USER || '';
    const id = createHash('sha256').update(['boundary', fromDir, toDir, author, createdAt].join('|')).digest('hex').slice(0, 8);
    if (readSeeds(store).boundaries.some(bd => bd.id === id)) return [`boundary ${id} already exists — \`grain seed rm ${id}\` first to change it`, stamp()];
    const mg = model.moduleGraph; const existing = (mg?.edges || []).filter(e => (e.from + '/').startsWith(fromDir + '/') && (e.to + '/').startsWith(toDir + '/'));
    mkdirSync(store.base, { recursive: true }); ensureSeedAttrs(store);
    appendFileSync(store.seedsPath, JSON.stringify({ id, boundary: { from: fromDir, to: toDir }, note: opts.note || '', author, createdAt }) + '\n');
    appendDecision(store, { action: 'add-boundary', id, at: createdAt, by: author, note: opts.note || '' });
    return [`recorded boundary ${id} in .grain/seeds.jsonl — ${fromDir}/ never imports ${toDir}/. ${existing.length ? `NOTE: the graph already holds ${existing.length} module edge(s) crossing it (${existing.slice(0, 3).map(e => `${e.from}→${e.to} ×${e.n}`).join(' · ')}) — existing code is a transition, new code will be flagged by \`check\`.` : 'No existing edges cross it.'} Commit .grain/seeds.jsonl and .grain/decisions.jsonl.`, stamp()]; }
  throw new Error('usage: grain seed add|add-boundary|list|rm …'); }
// the indexed scopes of HEAD (tree cache, or the scope snapshot of a git-less repo); a missing cache is rebuilt once
async function loadScopes({ root, isGit, store, opts }) {
  let treeCache = readJson(store.treePath); let snap = treeCache ? null : readJson(store.scopesPath);
  if (!treeCache && !snap) { log('scope cache missing — rebuilding it'); await ensureFresh({ root, isGit, store, opts, want: 'force' }); treeCache = readJson(store.treePath); snap = treeCache ? null : readJson(store.scopesPath); }
  return treeCache ? Object.values(treeCache).flatMap(v => Array.isArray(v) ? v : v.s) : (snap || []); }
// the whole model as data — see export.mjs
async function cmdExport({ model, meta, head, root, isGit, opts, stamp, store }) {
  const scopesAll = await loadScopes({ root, isGit, store, opts });
  let H = null; if (isGit && !opts['no-history']) { try { H = (await loadHistory({ gitdir: root, store, log })).H; } catch (e) { log('history unavailable for export: ' + e.message); } }
  const dump = exportModel({ model, root, scopesAll, H, meta, head, maxSites: opts['max-sites'] !== undefined ? +opts['max-sites'] : 300, anchors: !opts['no-anchors'] });
  const text = JSON.stringify(dump, null, opts.compact ? 0 : 1);
  if (opts.out) { const p = isAbsolute(opts.out) ? opts.out : resolve(process.cwd(), opts.out); atomicWrite(p, text);
    return [`export ${p} — ${dump.summary.conventions} conventions · ${dump.summary.groups} groups · ${dump.summary.deviations} deviating sites · ${dump.cochange.length} co-change pairs · ${(text.length / 1048576).toFixed(1)} MB`, stamp()]; }
  console.error('[grain] ' + stamp()); return [text]; }
function freshnessLines(meta, head, isGit) {
  const l = [];
  if (!isGit) l.push('freshness: no git repository — index keyed on file sizes/mtimes');
  else l.push(`freshness: indexed HEAD ${short(meta?.headSha)} · current HEAD ${short(head)} · ${meta?.headSha === head ? 'up to date' : 'STALE'} · history ${meta?.historyMode || '?'}${meta?.historyReason ? ` (${meta.historyReason})` : ''}`);
  if (meta) l.push(`index: engine ${meta.engine} · extractor ${meta.extractor} · grammars ${meta.grammars} · built ${meta.builtAt} in ${meta.buildMs}ms`);
  return l; }
export async function cmdStatus({ model, meta, head, isGit, stamp, opts, store }) { const sig = signal(model);
  if (opts.json) return [JSON.stringify({ repo: model.repo, files: model.files, partitions: model.partitions.map(p => ({ name: p.name, label: scopeLabel(p.name), files: p.files.length, scopes: p.scopes, groups: p.medoids.length, conventions: p.facts.length })), signal: sig, agentShare: model.agentShare, cochangePairs: model.cochange.length, history: model.historyStats, freshness: { indexedHead: meta?.headSha || null, head, upToDate: meta?.headSha === head, historyMode: meta?.historyMode || null, builtAt: meta?.builtAt || null, engine: meta?.engine, extractor: meta?.extractor }, asOf: stamp().replace(/^as of /, '') })];
  return [...statusLines(model), `signal: ${sig.facts} conventions over ${sig.files} source files — ${sig.verdict}`, ...placementOutcomeLine(store), ...freshnessLines(meta, head, isGit), stamp()]; }
// self-observability, not a repo convention — belongs beside status's own freshness/health lines, not in `report`'s
// "here is what this repo practices" surface. Silent (no "0 of 0" noise) until at least one suggestion has resolved.
function placementOutcomeLine(store) {
  const out = readJson(join(store.dir, 'placement-outcomes.json'));
  const total = out ? out.followed + out.deviated : 0;
  return total ? [`placement notes followed: ${out.followed} of ${total} (${Math.round(out.followed / total * 100)}%)`] : []; }
export async function cmdReport({ model, meta, head, isGit, opts, stamp }) {
  if (opts.json) return [JSON.stringify({ repo: model.repo, partitions: model.partitions.map(p => ({ name: p.name, label: scopeLabel(p.name), conventions: p.facts.slice(0, +opts.top || 15).map(f => ({ id: p.name + '::' + f.cid + '::' + f.pid, context: factLabel(p, f), kind: f.kind, pid: f.pid, expected: f.exp, statement: verbalize(f, f.exemplars.map(e => e.name)), share: f.share, established: f.sraw, deviantsN: f.deviantsN, deviants: f.deviants || [], exemplars: f.exemplars, trend: f.trend ? { shares: f.trend.shares.map(x => x.share), nucleating: f.trend.nucleating } : null, held: f.held || null })), total: p.facts.length })), asOf: stamp().replace(/^as of /, '') })];
  return [...report(model, { top: +opts.top || 15 }), ...freshnessLines(meta, head, isGit), stamp()]; }
// a generated Markdown document for a reader with no terminal and no grain plugin (a human maintainer, or a
// coding tool this plugin is not installed in) — the same model data `report()` renders, formatted as a
// standalone snapshot instead of context-window lines. `--out` writes the file and answers with a short
// confirmation only (never both the file AND the whole document on stdout); with no `--out`, the document goes
// straight to stdout so `grain rules > CONVENTIONS.md` already works without a flag — matching `export`'s own
// `--out`-vs-stdout split, including keeping the freshness stamp off stdout in the redirection path so it never
// lands inside the written document.
async function cmdRules({ model, isGit, head, opts, stamp }) {
  const text = rulesMarkdown(model, { top: +opts.top || 15, sha: short(isGit ? head : null), date: new Date().toISOString().slice(0, 10) }).join('\n');
  if (opts.out) { const p = isAbsolute(opts.out) ? opts.out : resolve(process.cwd(), opts.out); atomicWrite(p, text + '\n');
    const n = model.partitions.reduce((a, pt) => a + pt.facts.length, 0);
    return [`wrote ${n} convention(s) to ${p}`, stamp()]; }
  console.error('[grain] ' + stamp()); return [text]; }

// how much the model can say about the code, as a verdict a reader can calibrate on — "16 conventions over 150 files"
// is a sparse model and the agent cannot know that from the count alone
export function signal(model) {
  const src = model.partitions;
  const facts = src.reduce((a, p) => a + p.facts.length, 0), groups = src.reduce((a, p) => a + p.medoids.length, 0), files = src.reduce((a, p) => a + (p.files || []).length, 0);
  const per100 = files ? facts / files * 100 : 0;
  const verdict = !src.length ? 'no source partition — nothing is spoken here' : facts === 0 ? 'an empty model — placement only, no shape; read an exemplar' : per100 < 8 ? 'a sparse model — expect placement, not shape; read an exemplar' : per100 < 25 ? 'a moderate model' : 'a rich model';
  return { facts, groups, files, verdict }; }

// ----- session-context: what the SessionStart hook injects (no refresh, no parsing — must be instant) -----
export function sessionContext({ root, isGit, store, mode }) {
  const meta = readJson(store.metaPath); const model = meta && existsSync(store.modelPath) ? readJson(store.modelPath) : null;
  const head = isGit ? headSha(root) : null;
  let state;
  if (!isGit && !model) state = 'not built yet — the first query builds it (no git here, so weights will be flat)';
  else if (!model) state = `not built yet — the first query walks the full git history and parses every file; on a multi-thousand-commit or densely-scoped repo this can run minutes, not seconds, and a tight command timeout may mistake that for a hang; run \`grain refresh\` ahead of time, or add \`--no-history\` for a fast first answer without the history layer (later refreshes are incremental)`;
  else { const sig = signal(model);
    state = `${meta.headSha === head ? 'ready' : 'built at ' + short(meta.headSha) + ', HEAD moved to ' + short(head) + ' — the first query refreshes it incrementally'}: ${model.files} files, ${sig.groups} groups, ${sig.facts} conventions in source code (${sig.verdict})`; }
  const bin = `node "${BIN}"`;
  const text = [
    `grain is available here: a convention oracle mined from this repo's code and git history. It names WHICH directory, group, marker or file to open and the exemplar to copy, with evidence — then open that exemplar. Run from the repo root via Bash; every answer ends with \`as of <sha>\`.`,
    `  ${bin} where <intent words>   — before creating a source file or when unsure where something belongs; use the repo's own words (a decorator, a base type, a file or function name). One call per intent; a compact map = no hit: open the closest entry, do not re-ask with synonyms.`,
    `  ${bin} check <file>           — after you wrote or edited a file: deviations IN YOUR CHANGE (evidence + exemplars); pre-existing ones folded. Zero deviations is not a review.${mode === 'claude' || mode === 'codex' ? ' Runs automatically after every edit in this session — a [grain] note after an edit is this; silence means nothing certified to say, NOT approval.' : ''}`,
    `  ${bin} status | report        — size, freshness, top conventions.`,
    `Index: ${state}.`,
    ...(model && model.moduleGraph && model.moduleGraph.edges.length ? [(() => { const mg = model.moduleGraph;
      const sinks = new Map(); for (const e of mg.edges) sinks.set(e.to, (sinks.get(e.to) || 0) + e.n);
      const core = [...sinks].sort((a, b) => b[1] - a[1]).slice(0, 2).map(([m]) => m + '/').join(', ');
      return `Architecture (measured): ${mg.nodes.length} modules, ${mg.edges.length} dependencies, ${mg.cycles.length} cycle(s); most depended-on: ${core}. \`grain report\` prints the graph.`; })()] : []),
    ...(model && model.steers && model.steers.filter(st => st.found).length ? [(() => { const act = model.steers.filter(st => st.found);
      return `Maintainer decisions in force (committed .grain/seeds.jsonl — follow them even where the numbers lag; \`grain seed list\`): ${act.slice(0, 3).map(st => st.note || st.topic || st.id).join(' · ')}${act.length > 3 ? ` · +${act.length - 3} more` : ''}`; })()] : []),
  ].join('\n');
  if (mode === 'copilot') return { additionalContext: text };
  if (mode === 'cursor') return { additional_context: text };
  return { hookSpecificOutput: { hookEventName: 'SessionStart', additionalContext: text } }; }

// hooks receive a JSON payload on stdin ({ cwd, session_id, … }); read it only when stdin is a pipe with data
function hookCwd() { try { if (process.stdin.isTTY) return null; const raw = readFileSync(0, 'utf8'); if (!raw.trim()) return null; const j = JSON.parse(raw); return typeof j.cwd === 'string' ? j.cwd : null; } catch { return null; } }

// ----- placement feedback loop: a purely local, never-transmitted signal for whether a PreToolUse placement
// suggestion (placementHit, core.mjs) was actually followed. Two small state files in the same store dir as
// hook-seen.json: placement-pending.json (a suggestion awaiting its outcome) and placement-outcomes.json (a
// cumulative { followed, deviated } tally — latest state, not a history, exactly like hook-seen.json keeps
// only the latest signature per file rather than every past one).
//
// Correlation is by SUFFIX + NAME-KIN TOKEN (`sufOf`/`nameTokens`, core.mjs — the same keys placementHit itself
// groups candidates by), never by the exact `rel` grain was asked about. A single Write's PreToolUse and
// PostToolUse always see the IDENTICAL path, and placementHit only ever fires when that path's CURRENT
// directory does NOT already hold the name-kin — so resolving against that same `rel` can mathematically never
// observe "followed" (dirname(rel) was already established as wrong the moment Pre looked at it). The real
// "followed" case is a SEPARATE, corrective write at a DIFFERENT path — whose own PreToolUse finds no hit at
// all, since the destination is already correct. Keying by suffix+token lets that second, differently-pathed
// write still find the first write's pending suggestion.
//
// The pending window reuses GRAIN_HOOK_TTL_MS rather than a second constant: a placement suggestion is only
// actionable while the agent is still working that same name-kin file, which is the same timescale the hook's
// own repeat-suppression already models — a separate "how long is a suggestion live" number would track the
// same thing under a different name.
function pendingKey(suf, token) { return suf + '#' + (token || ''); }
function prunePending(pending, now, ttl) { for (const k of Object.keys(pending)) if (now - pending[k].t >= ttl) delete pending[k]; }
function recordPlacementPending(st2, ph, rel) {
  try {
    const now = Date.now(); const ttl = +(process.env.GRAIN_HOOK_TTL_MS || 15 * 60 * 1000);
    const p = join(st2.dir, 'placement-pending.json'); const pending = readJson(p) || {};
    prunePending(pending, now, ttl); pending[pendingKey(ph.suf, ph.token)] = { dir: ph.dir, t: now, badRel: rel };
    writeFileSync(p, JSON.stringify(pending)); }
  catch { /* stateless is still correct, just louder */ } }
function resolvePlacementPending(st2, root, rel) {
  try {
    if (!existsSync(join(root, rel))) return; // only a confirmed write can resolve anything
    const now = Date.now(); const ttl = +(process.env.GRAIN_HOOK_TTL_MS || 15 * 60 * 1000);
    const p = join(st2.dir, 'placement-pending.json'); const pending = readJson(p) || {};
    prunePending(pending, now, ttl);
    const suf2 = sufOf(rel); const dir2 = posixDirname(rel);
    const keys = [pendingKey(suf2, null), ...nameTokens(rel).map(t => pendingKey(suf2, t))];
    for (const k of keys) { const entry = pending[k]; if (!entry) continue;
      if (rel === entry.badRel) { bumpOutcome(st2, 'deviated'); delete pending[k]; }
      else if (dir2 === entry.dir) { bumpOutcome(st2, 'followed'); delete pending[k]; }
      // else: a second miss on the same suffix/token — leave it pending, don't guess, don't double-count
    }
    writeFileSync(p, JSON.stringify(pending)); }
  catch { /* stateless is still correct, just louder */ } }
function bumpOutcome(st2, kind) {
  const op = join(st2.dir, 'placement-outcomes.json'); const outcomes = readJson(op) || { followed: 0, deviated: 0 };
  outcomes[kind]++; writeFileSync(op, JSON.stringify(outcomes)); }

// ----- main -----
export async function main(argv) {
  const { cmd, args, opts } = parseArgv(argv);
  const { root, git: isGit } = findRoot(opts); const store = storeFor(root);
  if (!cmd || cmd === 'help' || opts.help) { console.log(USAGE); return 0; }
  if (cmd === 'session-context') { // hook path: never fails the session, never rebuilds, honours the host's cwd from the stdin payload
    try { let r = { root, isGit, store }; const cwd = hookCwd(); if (cwd && cwd !== process.cwd()) { const f = findRoot({ repo: cwd }); r = { root: f.root, isGit: f.git, store: storeFor(f.root) }; }
      console.log(JSON.stringify(sessionContext({ ...r, mode: opts.mode || args[0] || 'claude' }))); }
    catch (e) { console.error('[grain] session-context failed: ' + e.message); }
    return 0; }
  if (cmd === 'check-hook') { // PostToolUse hook: grain comes to the agent after every edit — speaks ONLY when it has
    // findings on the touched lines (deviations, maintainer decisions, architecture), never builds or refreshes, never blocks
    try {
      let payload = null; try { if (!process.stdin.isTTY) { const raw = readFileSync(0, 'utf8'); if (raw.trim()) payload = JSON.parse(raw); } } catch { /* no payload → nothing to check */ }
      const fp = payload?.tool_input?.file_path || payload?.tool_input?.filePath || payload?.file_path;
      if (!fp) return 0;
      const f = findRoot({ repo: typeof payload?.cwd === 'string' ? payload.cwd : process.cwd() }); const st2 = storeFor(f.root);
      const fpr = canonicalize(fp);
      const meta2 = readJson(st2.metaPath); const model2 = meta2 && existsSync(st2.modelPath) ? readJson(st2.modelPath) : null;
      if (!model2 || meta2.engine !== ENGINE_VERSION || meta2.extractor !== EXTR_V || (meta2.model || '') !== MODEL_V) return 0; // stale schema: silence, the next real query rebuilds
      const rel = relPath(f.root, fpr);
      const stamp2 = d => `as of ${short(meta2.headSha)}${d ? '+dirty' : ''}`;
      let speak; let pre = false;
      if (opts.pre) { // PreToolUse on Write: the file does not exist yet — placement speaks from the PATH alone, BEFORE
        // the worker sinks cost into the wrong directory (measured, replay-3: a post-write note was followed only while
        // moving was still cheap; the stronger, later note lost to sunk cost)
        pre = true;
        const ph = placementHit(model2, rel);
        if (ph) recordPlacementPending(st2, ph, rel); // feedback loop: did a later write to this suffix/token land in `ph.dir`? resolved on a matching PostToolUse below
        speak = ph ? [ph.text] : []; }
      else {
        resolvePlacementPending(st2, f.root, rel); // silent — never adds to the hook's spoken output, only updates local state
        if (!EXT2GRAMMAR[extname(rel)] || !existsSync(join(f.root, rel))) return 0;
        const lines = await cmdCheck({ model: model2, root: f.root, isGit: f.git, args: [rel], opts: {}, stamp: stamp2 });
        speak = lines.filter(l => l.includes('[grain]')); // only findings — headers, conforms-to and the stamp stay in the direct command
        // co-change: a separate, single-line finding — capped to 3 partners, folded into the same signature/suppression
        // below as the check findings, so it speaks unbidden but repeats no more often than they do
        const cc = completenessDirectional(model2, [rel]);
        if (cc.length > 1) speak = [...speak, `[grain] edits like this also touch: ${cc.slice(1, 4).map(l => l.replace(/^\s*-\s*/, '')).join(' · ')}`]; }
      if (!speak.length) return 0;
      // repeat suppression: an agent editing the same file five times must not read the same note five times — an
      // UNCHANGED set of findings for a file repeats only after the TTL; any change in the findings speaks at once
      const TTL = +(process.env.GRAIN_HOOK_TTL_MS || 15 * 60 * 1000);
      const sig = createHash('sha256').update(rel + '\n' + speak.join('\n')).digest('hex').slice(0, 16);
      const seenPath = join(st2.dir, 'hook-seen.json'); const seen = readJson(seenPath) || {};
      const prev = seen[rel]; const now = Date.now();
      if (prev && prev.h === sig && now - prev.t < TTL) return 0;
      try { seen[rel] = { h: sig, t: now }; writeFileSync(seenPath, JSON.stringify(seen)); } catch { /* stateless is still correct, just louder */ }
      const text = [...speak.slice(0, 8), ...(speak.length > 8 ? [`  (+${speak.length - 8} more — run \`grain check ${rel}\`)`] : []), stamp2(true)].join('\n');
      console.log(JSON.stringify(pre
        ? { hookSpecificOutput: { hookEventName: 'PreToolUse', permissionDecision: 'allow', additionalContext: text } }
        : { hookSpecificOutput: { hookEventName: 'PostToolUse', additionalContext: text } })); }
    catch (e) { if (process.env.GRAIN_DEBUG) console.error('[grain] check-hook: ' + (e?.stack || e)); /* a hook never breaks an edit */ }
    return 0; }
  if (cmd === 'version') { console.log(`grain ${ENGINE_VERSION} · extractor ${EXTR_V} · grammars ${GRAMMARS.join(', ')}`); return 0; }
  const want = cmd === 'refresh' ? 'force' : (opts['no-refresh'] || process.env.GRAIN_NO_REFRESH ? 'none' : 'refresh');
  const { model, meta, head, banner, stale } = await ensureFresh({ root, isGit, store, opts, want });
  if (!model) { console.log(banner.join('\n')); return 2; }
  const stamp = dirty => `as of ${short(stale ? meta?.headSha : head)}${dirty ? '+dirty' : ''}${stale ? ' (STALE)' : ''}`;
  const ctx = { model, meta, head, root, isGit, args, opts, stamp, store };
  let lines;
  switch (cmd) {
    case 'where': lines = await cmdWhere(ctx); break;
    case 'check': lines = await cmdCheck(ctx); break;
    case 'review': lines = await cmdReview(ctx); break;
    case 'spectrum': lines = await cmdSpectrum(ctx); break;
    case 'status': lines = await cmdStatus(ctx); break;
    case 'report': lines = await cmdReport(ctx); break;
    case 'rules': lines = await cmdRules(ctx); break;
    case 'export': lines = await cmdExport(ctx); break;
    case 'seed': lines = await cmdSeed(ctx); break;
    case 'refresh': lines = [...statusLines(model), ...freshnessLines(meta, head, isGit), stamp()]; break;
    case 'completeness': lines = [...completenessDirectional(model, args.map(a => relPath(root, a))), stamp()]; break;
    case 'mutate-test': lines = [JSON.stringify(await mutateTest({ model, root }), null, 1), stamp()]; break; // dev harness
    default: throw new Error(`unknown command "${cmd}"\n${USAGE}`); }
  console.log([...banner, ...lines].join('\n'));
  return 0; }

const USAGE = `grain — ask a repository about its own conventions before writing code.
usage: grain <command> [args] [--repo <path>] [--no-refresh] [--no-history]
  where <intent words> [--top N] [--map-rows N] [--json]  intent → place + expectations + exemplars + co-change
  check <file> [--as <path>] [--content <file>] [--all] [--json]  how this file's worktree version sits against the local norm
  review [--staged | --range <a>..<b> | --worktree] [--json]  one aggregated report over every file in your whole change (default: uncommitted + untracked)
  completeness <file…>                    other files this repo's own commits show reliably changing WITH these — the same line check-hook appends automatically after a matching edit
  spectrum <file> [--minbits N] [--top N] the full local→global convention lattice for one file
  status | report [--top N] [--json]      model overview / top conventions, freshness
  rules [--out <file>] [--top N]          a generated Markdown document of established conventions, stamped with the commit — for a
                                          reader with no terminal or no grain plugin; \`grain rules > CONVENTIONS.md\` also works
  export [--out <file>] [--max-sites N] [--compact] [--no-anchors]  the whole model as JSON: every convention with all its sites, anchors, trends,
                                          groups, markers, directories, co-change (for training pipelines and audits)
  seed add <path>#<name> --surfaces <pid,…> [--instead-of <pid,…>] [--author <who>] --note "…"   record a maintainer decision (.grain/seeds.jsonl, committed)
  seed add-boundary <from> --never-imports <to> --note "…"   an architecture decision: new imports crossing it are flagged
  seed list | seed rm <id>                the decisions in force / withdraw one
  refresh [--full]                        rebuild the index now (every query already auto-refreshes)
  version                                 engine, extractor and grammar versions
Index: <repo>/.grain/cache/ (gitignored, disposable). Every answer ends with \`as of <sha>[+dirty]\`.`;
