// grain engine · proposal writer · provenance, and the status an aspect earns from a real drill
// Split out of propose.mjs (ticket 124): the statements below are the ones that stood there, unchanged.
import { spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { preambleComment, resolveYg, write, yamlEmit } from './propose-base.mjs';
import { SYMBOL_LEVEL_KIND } from './propose-classify.mjs';
import { DRAFT_NOTE, statusNote } from './propose-lattice.mjs';

// ==================================================================================================
// 7a. `provenance.json` — one per rendered aspect (ticket 100 / law-loop-yggdrasil.md §1.2).
//
// SAME FIELD SET 097's `law-loop.mjs` `provenanceFor` writes for a candidate it renders from a CUT export, so a
// consumer (a human, or a future measurement) reads one shape whether the aspect came from a live `propose` run
// or from a held-out replay. The two differ only in HOW the fields are obtained: 097 regex-parses them back out
// of a written `provenance` prose string because it loads a proposal a PAST run already wrote to disk; here the
// renderer has the structured numbers on hand at write time (`a.partition`, `a.share`, `a.n`, `a.deviating` —
// added to the aspect object above for exactly this) and writes them directly, never through a regex.
//
// `status`, `draftReason` and `scopeApproximation` (ticket 102) are ADDED here, not shared with law-loop.mjs's
// own `provenanceFor` — they describe something only a LIVE run with a real `.yggdrasil/` tree on disk can know
// (a real `yg drill` result), which a held-out replay never produces. Additive, per the proposal contract's own
// rule (docs/reference.md): a field gained here is not a shape change to an existing one.
export function provenanceFor(a, { asOf, repo }) {
  return {
    aspectId: a.id,
    conventionId: a.id,
    origin: a.origin,
    enumeratorClass: a.enumerator ?? null,
    identifier: a.argument ?? null,
    expected: a.expected ?? null,
    // 'absence' when this row's class spells "does not use X" and its expected value is `false` — the one
    // direction whose sentence a reader must not read as a prohibition (ticket 115); null otherwise.
    direction: a.direction ?? null,
    partition: a.partition ?? null,
    share: a.share ?? null,
    n: a.n ?? null,
    deviating: a.deviating ?? null,
    // The same number as `deviating`, named for the question a maintainer switching this graph on is actually
    // asking (ticket 118): how much of the code that is already here does this rule refuse on day one? For an
    // `enforced` rule that is what the first `yg check` blocks on unless progressive mode is set; the field is
    // written for every aspect so a consumer never has to know which statuses carry it.
    existingViolations: a.deviating ?? null,
    asOf: asOf || null,
    cutSha: asOf || null, // a live `propose` run has no hold-out cut of its own — the cut IS `asOf` (HEAD)
    cutDate: null,
    repo,
    reviewer: a.check ? 'deterministic' : 'llm',
    note: a.check
      ? 'Generated by grain from measured practice at `asOf`; rendered as a deterministic check.mjs.'
      : 'Generated by grain from measured practice at `asOf`; no template renders this class as a deterministic check, so it ships as prose (content.md) for an LLM reviewer.',
    // 'enforced' | 'advisory' | 'draft' (ticket 107) — the SAME three values Yggdrasil's own `yg-aspect.yaml`
    // `status:` field takes (`yg schemas read aspect`), written here verbatim, not a separate Grain-internal
    // word translated at write time. Absent only if this ran before classification ran at all.
    status: a.finalStatus ?? 'draft',
    // one of 'prose-unenforceable-keyless' | 'absence-not-forbiddance' | 'file-scope-approximation-fa' |
    // 'no-catch', or null when `status` is 'enforced'/'advisory' (nothing to explain) or the aspect was never
    // verified this run (no `YG_BIN`, no drill corpus). 'absence-not-forbiddance' is set BEFORE verification —
    // it is the one reason that says the row was never eligible to earn a status at all (ticket 115).
    draftReason: a.draftReason ?? null,
    // 'file-from-symbol' when the CONVENTION's own subject (`a.kind`) is a symbol inside a file — a method, a
    // type, a catch/finally block — but Yggdrasil reviews this check per FILE; null for a file/module-level
    // convention, where the unit the check runs at and the unit the convention is ABOUT are the same thing.
    scopeApproximation: a.scopeApproximation ?? null,
  };
}
// WHAT THE STATUS DOES, IN ONE SENTENCE, BESIDE THE RULE (ticket 109). `status: advisory` is a word whose
// consequence lives in a knowledge topic (`yg knowledge read aspect-status`) that a session reading one aspect
// file has not opened. The three sentences below are that topic's own table, said in the place the decision is
// made — so an agent asked to obey a rule knows what happens if it does not, and a maintainer deciding whether
// to keep the rule knows what turning it on costs. Nothing else in the file changes by status.
const STATUS_MEANING = {
  enforced: 'This rule is in force: `yg check` reports a file that breaks it as an error and fails.',
  advisory: 'This rule is advisory: `yg check` reports a file that breaks it as a warning and does not fail.',
  draft: 'This rule is not in force yet: `yg check` skips it entirely until someone promotes it out of `draft`.',
};
// The `yg-aspect.yaml` document, shared by the provisional (`draft`, before verification) and final write.
export function aspectYamlDoc(a, status) {
  return {
    '#e': a.evidenceLine,
    name: a.name, description: `${a.description} ${STATUS_MEANING[status] || ''}`.trim(), status,
    ...(a.check ? { errs: 'under' } : {}),
    review_by: a.reviewBy,
    scope: a.scope,
  };
}
// ==================================================================================================
// 7a-continued. Aspect status, earned rather than declared (ticket 102, sharpened by ticket 107's ruling
// `enforced-requires-certified-origin`). Sits right after `provenanceFor` (§7a) rather than claiming its own
// top-level number — §7b/§7c below (the family-candidates adapter, `charter.md`) are ticket 100's, unrenumbered.
//
// `status: draft` is where every aspect starts (§ above). `a.finalStatus` below is written directly in
// Yggdrasil's own vocabulary (`enforced` | `advisory` | `draft` — `yg schemas read aspect`), not a separate
// Grain-internal word translated at write time: `provenanceFor` and every evidence row read it verbatim. This
// function is the only place anything leaves `draft`:
//
//   - PROSE (`content.md`) never leaves. Ticket 101 measured its sense rate under a keyless gate at 0% (1305 of
//     1671 proposed aspects on a 17-repo corpus) — a judgment call needs a configured reviewer this renderer
//     cannot assume, so it ships as a candidate for a human decision, always (`prose-unenforceable-keyless`).
//   - A DETERMINISTIC check (`check.mjs`) is judged by a REAL `yg drill` run against the proposal this renderer
//     JUST wrote, in a throwaway staging copy — never against a claim this script computes on its own. `yg
//     drill` needs nothing but a `.yggdrasil/` tree at its cwd (status does not gate it — `yg knowledge read
//     aspect-status`), so the stage is exactly that tree, nothing more.
//     - `FALSE-ALARM > 0` → stays draft, `file-scope-approximation-fa`. Ticket 101 §8.1 traced every remaining
//       FALSE-ALARM in its whole corpus to one shape: the convention's subject is a symbol inside a file (a
//       method, a type), the check's unit is the file, and a drill corpus cut from a SAMPLE of sites mislabels
//       the file. Ruling `drill-fa-labelling-is-acceptance-not-defect`: this is a corpus-labelling artifact, not
//       a defect to chase here, and the fix is to demote, not to relabel — 0 is not a matter of taste, it is the
//       only value at which a keyless CI never blocks on an honest change.
//     - Else, `catches (violates-case refusals) <= 0` → stays draft, `no-catch`. Ruling `no-catch-rules-stay-
//       draft`: a rule nothing can ever be shown to violate does not enforce architecture — it is noise for a
//       future agent session, whatever else is true about it.
//     - Else (0 FALSE-ALARM, >= 1 catch): the drill has proved `check.mjs` CORRECT — but `no-catch-rules-stay-
//       draft` and this drill only ever measure whether the check is right, never whether the rule is ADOPTED.
//       `origin: certified-convention` (the row cleared grain's own MDL/λ certification bound) → `enforced`:
//       nothing stands between the maintainer and turning it on. `origin: sub-gate-lattice` (the row sits
//       BELOW that bound — grain itself refused to certify it; ruling `sub-gate-rows-are-the-product`, a
//       lattice row is a refactor plan, not law) → `advisory` instead: Yggdrasil runs the same reviewer and
//       records the same baseline, but a refusal warns rather than blocks (`yg schemas read aspect`). Ruling
//       `enforced-requires-certified-origin`: on Grain's own young, uncertified repo EVERY sub-gate row that
//       passed this exact drill (22 of 22) would otherwise have gone straight to `enforced`, including rules
//       practised in as little as 67% of sites with a third of sites deviating — turning `yg check` red on a
//       third of the existing code for a rule grain itself would not certify.
//   - No `YG_BIN`, or a check with no drill corpus at all (nothing to run) → stays draft, unverified, no reason.
//     Exactly what this renderer shipped before ticket 102 — the absence of a verdict is not one of the three
//     named reasons above, because none of them fired; nothing here says the check is bad, only that no drill
//     was run to say either way.
// HOW LONG ONE `yg drill` MAY TAKE BEFORE IT IS ABANDONED, AND WHERE THE NUMBER COMES FROM.
//
// `spawnSync` with no `timeout` waits forever. A drill that does not return — a wedged CLI, a filesystem that
// stops answering, a pathological regex in a rendered check — therefore hung `grain propose` itself, silently,
// with no output and nothing to interrupt but the process. A product command may not have that failure mode.
//
// The bound is DERIVED, not chosen. A drill's whole input is bounded by construction: `cutDrills` writes at
// most 5 `satisfies-` and 5 `violates-` cases and skips any source file over 200 KiB, so the work does not grow
// with the size of the repository being proposed on — only the machine and the grammar load vary. Measured on
// the largest proposal this project renders (Yggdrasil's own, 33 deterministic aspects carrying a drill
// corpus): slowest single drill 2148 ms, median 1420 ms. The ceiling is that slowest observed drill x100, so it
// is reached only by a machine two orders of magnitude slower than the one measured on, or by a drill that is
// not progressing at all. A drill that hits it is reported as unverified — the same outcome as any other drill
// that returned no verdict — and the count is disclosed in the report rather than folded in silently.
export const SLOWEST_OBSERVED_DRILL_MS = 2148;
export const DRILL_TIMEOUT_MS = SLOWEST_OBSERVED_DRILL_MS * 100;
//
// `drillTimeoutMs` exists so a test can prove the bound is actually enforced without waiting out the real one;
// nothing in the product passes it, and the default IS `DRILL_TIMEOUT_MS`.
export function promoteEnforceableAspects(aspects, { ygg, outDir, evidence, asOf, repo, ygBin: explicitYgBin, drillTimeoutMs = DRILL_TIMEOUT_MS }) {
  const yg = resolveYg(explicitYgBin);
  const ygBin = yg.label;
  const haveYg = yg.have;
  const stage = join(outDir, '.grain-verify-stage');
  if (haveYg) {
    rmSync(stage, { recursive: true, force: true });
    mkdirSync(stage, { recursive: true });
    // `yg drill` reads only the aspect's own `check.mjs` and its `drills/{satisfies-*,violates-*}` corpus, both
    // already self-contained copies inside `.yggdrasil/aspects/<id>/` — no repository source tree is needed at
    // all (verified against the real CLI while designing this). A throwaway copy of the tree this renderer just
    // wrote, nothing else, and it is deleted again below whether or not verification ran to completion.
    cpSync(ygg, join(stage, '.yggdrasil'), { recursive: true });
  }

  let verified = 0, timedOut = 0;
  try {
    for (const a of aspects) {
      a.scopeApproximation = (a.check && a.kind && SYMBOL_LEVEL_KIND.has(a.kind)) ? 'file-from-symbol' : null;
      if (!a.check) { a.finalStatus = 'draft'; a.draftReason = a.draftReason || 'prose-unenforceable-keyless'; continue; }
      const violates = a.drillViolatesWritten || 0, satisfies = a.drillSatisfiesWritten || 0;
      if (!haveYg || (!violates && !satisfies)) { a.finalStatus = 'draft'; a.draftReason = null; continue; }
      const r = spawnSync(yg.cmd, [...yg.pre, 'drill', '--aspect', a.id], { cwd: stage, encoding: 'utf8', maxBuffer: 1 << 26, timeout: drillTimeoutMs, killSignal: 'SIGKILL' });
      if (r.error?.code === 'ETIMEDOUT') timedOut++;
      const m = /(\d+) pass\s*·\s*(\d+) MISS\s*·\s*(\d+) FALSE-ALARM/.exec(`${r.stdout || ''}${r.stderr || ''}`);
      if (!m) { a.finalStatus = 'draft'; a.draftReason = null; continue; } // could not verify this run (a spawn failure, or the timeout above) — unverified, not blamed
      verified++;
      const miss = Number(m[2]), falseAlarm = Number(m[3]);
      const catches = violates - miss;
      // The drill's own three numbers, kept on the aspect for whoever renders a report from this run. Nothing
      // on disk reads them (`provenanceFor` names its fields one by one), so a proposal tree is byte-identical
      // with and without this line — ticket 104 needs them to say what an enforced rule actually caught.
      a.drill = { pass: Number(m[1]), miss, falseAlarm, catches, violates, satisfies };
      if (falseAlarm > 0) { a.finalStatus = 'draft'; a.draftReason = 'file-scope-approximation-fa'; }
      else if (catches <= 0) { a.finalStatus = 'draft'; a.draftReason = 'no-catch'; }
      // The drill passed — 0 FALSE-ALARM, >= 1 caught. Whether that earns `enforced` or only `advisory` turns
      // on ORIGIN, not on anything the drill measured (ruling `enforced-requires-certified-origin`): a
      // certified convention cleared grain's own certification bound and is law; a sub-gate-lattice row sat
      // BELOW it — grain itself declined to certify it — and stays a maintainer's refactor decision.
      else { a.finalStatus = a.origin === 'certified-convention' ? 'enforced' : 'advisory'; a.draftReason = null; }
    }
  } finally {
    // Always — a thrown drill invocation must not leave a throwaway copy of the whole proposal sitting in the
    // maintainer's out-dir.
    if (haveYg) rmSync(stage, { recursive: true, force: true });
  }

  for (const a of aspects) {
    // `enforced` and `advisory` both leave `draft` and both need `yg-aspect.yaml` rewritten with the earned
    // status; `draft` aspects keep the file this renderer already wrote above (§7).
    if (a.finalStatus === 'enforced' || a.finalStatus === 'advisory') {
      write(join(ygg, 'aspects', a.id, 'yg-aspect.yaml'), preambleComment() + yamlEmit(aspectYamlDoc(a, a.finalStatus)));
      const checkPath = join(ygg, 'aspects', a.id, 'check.mjs');
      if (existsSync(checkPath)) {
        const text = readFileSync(checkPath, 'utf8');
        if (text.includes(DRAFT_NOTE)) write(checkPath, text.replace(DRAFT_NOTE, statusNote(a.finalStatus)));
      }
    }
    write(join(ygg, 'aspects', a.id, 'provenance.json'), JSON.stringify(provenanceFor(a, { asOf, repo }), null, 2) + '\n');
    const row = evidence.find(e => e.kind === 'aspect' && e.id === a.id);
    if (row) { row.status = a.finalStatus; row.draftReason = a.draftReason || null; }
  }
  return { haveYg, ygBin, verified, timedOut, drillTimeoutMs };
}
