// grain engine · history weighting (survival x provenance x churn), value trends and calibration
// Split out of core.mjs: the statements below are the ones that stood there, unchanged.
import { CFG } from './config.mjs';
import { isBool, skeyR } from './facts.mjs';

// ===== WEIGHTS FROM HISTORY (survival × provenance × churn, floor) =====
export function mkWeightFn(H) {
  if (!H) return { wfn: () => 1, ageFn: null, get: () => null };
  const filelvl = new Map();
  for (const [, L] of H.lc) {
    const p = L.path;
    let F = filelvl.get(p);
    if (!F) {
      F = { ...L };
      filelvl.set(p, F);
    } else {
      F.first = Math.min(F.first, L.first);
      if (L.last > F.last) {
        F.last = L.last;
        F.agentLast = L.agentLast;
      }
    }
  }
  const get = s => H.lc.get(skeyR(s.rel, s)) || filelvl.get(s.rel) || null;
  return {
    ageFn: s => {
      const L = get(s);
      return L ? (H.NOW - L.first) / 86400 : 0;
    },
    wfn: s => {
      const L = get(s);
      if (!L) return 0.3;
      const stable = Math.max(0, (H.NOW - L.last) / 86400),
        age = Math.max(0, (H.NOW - L.first) / 86400);
      // no continuous survival ramp: "old" is not extra evidence, and the absolute 120-day scale priced a young repo's
      // real conventions at ~20% of their size (measured on a private repo: 19 certified where spectrum saw the field full).
      // What still discounts: brand-new code (< freshDays ⇒ ×0.5), code rewritten right after birth (churn ⇒ ×0.25),
      // and agent-authored code promotes over promoteDays as before. "n of N established" remains age-gated separately.
      const ws = age < CFG.freshDays ? 0.5 : 1;
      const wp = L.agentLast
        ? CFG.agentBase + (1 - CFG.agentBase) * Math.min(1, stable / CFG.promoteDays)
        : 1;
      let w = Math.max(CFG.floor, ws * wp * (L.churn ? 0.25 : 1));
      return w;
    },
    get,
  };
}
// dimension value from a historical val snapshot, for trend/calibration-supported pids
export function valOf(pid, v) {
  if (pid === 'auto.nameshape') return v.ns;
  if (pid === 'auto.first1') return v.f1 || undefined;
  if (pid === 'auto.ret') return v.ret || undefined;
  if (pid.startsWith('auto.deco:@')) return v.deco.includes(pid.slice(11)) ? 'true' : 'false';
  if (pid.startsWith('auto.extends:')) return v.sup.includes(pid.slice(13)) ? 'true' : 'false';
  return undefined;
}
// drift and nucleation: an MDL change point on the arrival order of a fact's instances (docs/mathematics.md, "Drift
// and nucleation"). Instances are ordered by birth — the first history event whose value `valOf` can read — and the
// unit is the commit: a commit contributes one observation per distinct value it bore, coded 1 for the expected value
// and 0 for any other, so eleven accessors generated by one rename are one departure, not eleven. One KT code for the
// whole sequence is compared with two KT codes split at a commit boundary τ, plus log2 of the number of boundaries to
// name τ; KT is exchangeable, so each segment's code depends only on its counts and every τ costs O(1) after one
// pass. Indexed by commit order, never by calendar days, so a thirty-day repository with six hundred commits has a
// time axis. The gain returned here is raw: `settleChangePoints` pays the repository-wide index cost once every
// fact's candidate is known.
const LN2 = Math.log(2);
export function changePointFor(fact, ps, H) {
  const born = [];
  for (const gi of fact.conform.concat(fact.deviants.map(d => d.gi))) {
    const key = skeyR(ps[gi].rel, ps[gi]);
    const evs = H.vev.get(key);
    if (!evs || !H.lc.get(key)) continue;
    for (const e of evs) {
      const v = e.val ? valOf(fact.pid, e.val) : undefined;
      if (v === undefined) continue;
      born.push({ ts: e.ts, key, v });
      break;
    }
  }
  if (!born.length) return null;
  born.sort((a, b) => a.ts - b.ts || (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
  // one observation per (commit, value): a commit is identified by its timestamp here, as in `H.lc`
  const obs = [];
  for (let i = 0, j; i < born.length; i = j) {
    const vs = new Set();
    for (j = i; j < born.length && born[j].ts === born[i].ts; j++) vs.add(born[j].v);
    for (const v of [...vs].sort()) obs.push({ ts: born[i].ts, v, birth: i });
  }
  const n = obs.length;
  // ln Γ(k + ½) and ln Γ(k + 1) for k = 0..n, built by the recurrence Γ(x + 1) = x·Γ(x)
  const lgh = new Float64Array(n + 1),
    lgi = new Float64Array(n + 1);
  lgh[0] = Math.log(Math.PI) / 2;
  for (let k = 1; k <= n; k++) {
    lgh[k] = lgh[k - 1] + Math.log(k - 0.5);
    lgi[k] = lgi[k - 1] + Math.log(k);
  }
  // −log2 of the KT probability of a binary sequence with a ones and b zeros: Γ(a+½)·Γ(b+½) / (π·Γ(a+b+1))
  const ktBits = (a, b) => -(lgh[a] + lgh[b] - Math.log(Math.PI) - lgi[a + b]) / LN2;
  const pre = new Int32Array(n + 1);
  for (let i = 0; i < n; i++) pre[i + 1] = pre[i] + (obs[i].v === fact.exp ? 1 : 0);
  const A = pre[n];
  let exp = 0;
  for (const b of born) if (b.v === fact.exp) exp++;
  const whole = { end: born[born.length - 1].ts, share: +(exp / born.length).toFixed(2), n: born.length };
  let cuts = 0,
    best = Infinity,
    tau = -1;
  for (let t = 1; t < n; t++) {
    if (obs[t].ts === obs[t - 1].ts) continue; // one commit is never split
    cuts++;
    const l2 = ktBits(pre[t], t - pre[t]) + ktBits(A - pre[t], n - t - (A - pre[t]));
    if (l2 < best) {
      best = l2;
      tau = t;
    }
  }
  if (!cuts) return { gain: 0, whole };
  const gain = ktBits(A, n - A) - best - Math.log2(cuts);
  return { gain, whole, born, obs, tau };
}
// the repository-wide half of the change point: one index cost over every fact that had a boundary to cut at, then
// the λ bound read on the segment after τ. A convention whose recent births no longer carry it at the λ odds stops
// accusing (`fading`); a value that the recent births carry at those odds is reported as nucleating.
export function settleChangePoints(cands) {
  const tested = cands.filter(c => c.cp && c.cp.born);
  const idxCost = Math.ceil(Math.log2(Math.max(tested.length, 2)));
  for (const { f, cp } of cands) {
    if (!cp) continue;
    const trend = { shares: [cp.whole], attractor: f.exp, nucleating: null, fading: false };
    if (cp.born && cp.gain - idxCost > 0) {
      const { born, obs, tau } = cp,
        cut = obs[tau].birth; // the first birth after the cut
      // the λ bound after the cut is read on the same per-commit observations the cut was found on
      const post = Object.create(null),
        preObs = obs.slice(0, tau);
      for (const o of obs.slice(tau)) post[o.v] = (post[o.v] || 0) + 1;
      const m = obs.length - tau,
        K = isBool(f.pid) ? 2 : (f.alphabet || []).length + 1;
      const pk = v => ((post[v] || 0) + 0.5) / (m + K / 2);
      const nExp = bs => bs.filter(b => b.v === f.exp).length;
      trend.shares = [
        { end: born[cut - 1].ts, share: +(nExp(born.slice(0, cut)) / cut).toFixed(2), n: cut },
        {
          end: born[born.length - 1].ts,
          share: +(nExp(born.slice(cut)) / (born.length - cut)).toFixed(2),
          n: born.length - cut,
        },
      ];
      trend.since = born[cut].ts;
      trend.bits = +(cp.gain - idxCost).toFixed(2);
      const vs = Object.keys(post).sort((x, y) => post[y] - post[x] || (x < y ? -1 : 1));
      trend.attractor = vs[0];
      trend.fading = (post[f.exp] || 0) / m < nExp(preObs) / tau && pk(f.exp) < 1 - 1 / CFG.lambda;
      const nv = vs.find(v => v !== f.exp);
      if (nv !== undefined && pk(nv) >= 1 - 1 / CFG.lambda) trend.nucleating = nv;
    }
    f.trend = trend;
    if (!f.contested && trend.nucleating) f.suppressedValue = trend.nucleating;
  }
}
// the structural opposite of the change point's `nucleating`: a value TRIED on enough scopes and then REVERTED, never
// one quietly becoming the new norm. Per scope, decode `H.vev` chronologically via the SAME `valOf` the change point and
// calibrate already use — so this inherits their exact limitation, silent for every pid family outside the 5
// valOf decodes (nameshape/first1/ret/deco:@/extends:), documented by export.mjs's `valueTracked`. For each
// distinct v != fact.exp ever taken by a scope: if the scope's LAST decoded value is v, it survived (nucleation,
// never counted here); otherwise it tried and was reverted. Speaks when tried >= CFG.minRaw and reverted/tried >=
// 2/3 — the same supermajority proportion used throughout this codebase (altMarkerFor, placementHit, markerObs,
// authorConcentration, J3.4's twin threshold).
export function rejectedValues(fact, ps, H) {
  const keys = fact.conform.concat(fact.deviants.map(d => d.gi)).map(gi => skeyR(ps[gi].rel, ps[gi]));
  const tried = new Map(),
    reverted = new Map();
  for (const key of keys) {
    const evs = H.vev.get(key);
    if (!evs) continue;
    const decoded = [];
    for (const e of evs) {
      const v = valOf(fact.pid, e.val);
      if (v !== undefined) decoded.push(v);
    }
    if (!decoded.length) continue;
    const last = decoded[decoded.length - 1];
    for (const v of new Set(decoded.filter(x => x !== fact.exp))) {
      tried.set(v, (tried.get(v) || 0) + 1);
      if (last !== v) reverted.set(v, (reverted.get(v) || 0) + 1);
    }
  }
  const out = [];
  for (const [v, t] of tried) {
    const r = reverted.get(v) || 0;
    if (t >= CFG.minRaw && r / t >= 2 / 3) out.push({ v, tried: t, reverted: r });
  }
  out.sort((a, b) => b.tried - a.tried || (a.v < b.v ? -1 : a.v > b.v ? 1 : 0));
  return out.length ? out : undefined;
}
// calibration: temporal split, τ_c by point precision, DENY by Wilson LB (report-only in grain — nothing ever blocks)
export function calibrate(fact, ps, H) {
  const split = H.NOW - CFG.calibHorizonDays * 86400;
  const settle = H.NOW - CFG.calibSettleDays * 86400;
  if (H.firstTs > split) return { available: false, reason: 'history<horizon' };
  const evts = [];
  for (const gi of fact.conform.concat(fact.deviants.map(d => d.gi))) {
    const s = ps[gi];
    const key = skeyR(s.rel, s);
    const evs = H.vev.get(key);
    if (!evs) continue;
    for (let i = 1; i < evs.length; i++) {
      const e = evs[i];
      if (e.ts <= split || e.ts > settle) continue;
      const v = valOf(fact.pid, e.val);
      if (v === undefined || v === fact.exp) continue;
      let repaired = false;
      for (let j = i + 1; j < evs.length; j++)
        if (valOf(fact.pid, evs[j].val) === fact.exp) {
          repaired = true;
          break;
        }
      evts.push({ repaired });
    }
  }
  if (evts.length < CFG.calibMinEv)
    return { available: false, reason: `events ${evts.length}<${CFG.calibMinEv}`, events: evts.length };
  const p = evts.filter(e => e.repaired).length / evts.length;
  const z = 1.96,
    n = evts.length,
    lb =
      (p + (z * z) / (2 * n) - z * Math.sqrt((p * (1 - p)) / n + (z * z) / (4 * n * n))) / (1 + (z * z) / n);
  return {
    available: true,
    events: n,
    precision: +p.toFixed(2),
    wilsonLB: +lb.toFixed(2),
    tauC: p >= CFG.targetPrec ? Math.log2(CFG.lambda) : Math.log2(CFG.lambda) + 1.5,
    denyEligible: lb >= 0.9 && n >= CFG.denyMinEv,
  };
}
// the target of an `auto.extends:` pid, classified 'ext'/'impl' via model.heritageKind (built once in
// learn(), from extractScopes' own supKind — see bindingFor's extendsClauseRe/implementsClauseRe), or undefined
// where unclassified. One helper, reused at every fact-like object built ad hoc for a steer/waiver at render
// time, so it carries the same distinction a mined fact gets at its own construction site (learn()'s `ef`).
export function heritageKindOf(pid, model) {
  return pid.startsWith('auto.extends:') ? (model.heritageKind || {})[pid.slice(13)] : undefined;
}
