#!/usr/bin/env node
// queue — work queue. .system/queue.json is the source of truth; .system/queue.md
// is regenerated on every write for humans to read.
// Zero dependencies. Run from the repo root:
//   node .claude/skills/director/scripts/queue.mjs <command> [args] [--json] [--root <path>]
import { existsSync } from 'node:fs';
import {
  findRepoRoot, queueJsonPath, queueMdPath, readJSONSafe, writeJSON, writeText,
  fail, parseArgs, printTable, nowStamp,
} from './_lib.mjs';

const HELP = `queue — work queue over .system/queue.json (.system/queue.md is rendered from it)

Usage:
  queue list [--state s] [--json]
  queue add <ticket-or-name> --kind k --agent a --branch b [--note n] [--json]
  queue set <id|ticket> <state> [--sha x] [--note n] [--json]
  queue next [--agent a] [--kind k] [--json]
  queue rm <id> [--json]
  queue render
  queue --help

kind:  fix | instr | measure | research | explore
agent: sonnet | opus
state: queued | running | landed | merged | escalated | dropped
Global flags: --json    machine-readable output
              --root    override the auto-detected repo root (default: walk up to .git)
`;

export const KINDS = ['fix', 'instr', 'measure', 'research', 'explore'];
export const AGENTS = ['sonnet', 'opus'];
export const STATES = ['queued', 'running', 'landed', 'merged', 'escalated', 'dropped'];
const STATE_ORDER = STATES; // queued first, in declared order

export function loadQueue(root) {
  const path = queueJsonPath(root);
  if (!existsSync(path)) {
    if (existsSync(queueMdPath(root))) {
      console.error(`note: ${path} is missing but queue.md exists — starting from an empty queue (queue.md was not parsed)`);
    }
    return { items: [] };
  }
  const data = readJSONSafe(path, { items: [] });
  if (!Array.isArray(data.items)) throw new Error(`${path}: expected { items: [...] }`);
  return data;
}

function saveQueue(root, data) {
  writeJSON(queueJsonPath(root), data);
  renderMd(root, data);
}

export function renderMd(root, data) {
  const items = data.items;
  const lines = ['# Queue', '', '_Generated by queue.mjs — edit .system/queue.json, not this file._', ''];
  for (const state of STATE_ORDER) {
    const group = items.filter((i) => i.state === state).sort((a, b) => a.id - b.id);
    lines.push(`## ${state} (${group.length})`, '');
    if (group.length === 0) {
      lines.push('_none_', '');
      continue;
    }
    lines.push('| id | ticket | kind | agent | branch | sha | note | updated |');
    lines.push('|---|---|---|---|---|---|---|---|');
    for (const it of group) {
      lines.push(`| ${it.id} | ${it.ticket} | ${it.kind} | ${it.agent} | ${it.branch} | ${it.sha || ''} | ${it.note || ''} | ${it.updated || ''} |`);
    }
    lines.push('');
  }
  writeText(queueMdPath(root), lines.join('\n'));
}

function nextItemId(data) {
  const ids = data.items.map((i) => i.id).filter((n) => Number.isInteger(n));
  return ids.length ? Math.max(...ids) + 1 : 1;
}

export function addItem(root, { ticket, kind, agent, branch, note }) {
  if (!ticket) throw new Error('a ticket or name is required');
  if (!KINDS.includes(kind)) throw new Error(`--kind must be one of: ${KINDS.join(', ')}`);
  if (!AGENTS.includes(agent)) throw new Error(`--agent must be one of: ${AGENTS.join(', ')}`);
  if (!branch) throw new Error('--branch is required');
  const data = loadQueue(root);
  const item = {
    id: nextItemId(data), ticket, kind, agent, branch, state: 'queued',
    sha: undefined, note: note || undefined, updated: nowStamp(),
  };
  data.items.push(item);
  saveQueue(root, data);
  return item;
}

function findItem(data, idOrTicket) {
  const asNum = Number(idOrTicket);
  if (Number.isInteger(asNum) && String(asNum) === String(idOrTicket)) {
    const byId = data.items.find((i) => i.id === asNum);
    if (byId) return byId;
  }
  return data.items.find((i) => i.ticket === idOrTicket);
}

export function setItem(root, idOrTicket, state, { sha, note } = {}) {
  if (!STATES.includes(state)) throw new Error(`unknown state '${state}' — allowed: ${STATES.join(', ')}`);
  const data = loadQueue(root);
  const item = findItem(data, idOrTicket);
  if (!item) throw new Error(`no queue item matching '${idOrTicket}'`);
  item.state = state;
  if (sha !== undefined) item.sha = sha;
  if (note !== undefined) item.note = note;
  item.updated = nowStamp();
  saveQueue(root, data);
  return item;
}

export function removeItem(root, idOrTicket) {
  const data = loadQueue(root);
  const item = findItem(data, idOrTicket);
  if (!item) throw new Error(`no queue item matching '${idOrTicket}'`);
  data.items = data.items.filter((i) => i !== item);
  saveQueue(root, data);
  return item;
}

export function nextQueued(root, { agent, kind } = {}) {
  const data = loadQueue(root);
  return data.items.find((i) => i.state === 'queued' && (!agent || i.agent === agent) && (!kind || i.kind === kind)) || null;
}

export function summarizeQueue(root) {
  const data = loadQueue(root);
  const byState = {};
  for (const s of STATES) byState[s] = 0;
  for (const i of data.items) byState[i.state] = (byState[i.state] || 0) + 1;
  return { total: data.items.length, byState, running: data.items.filter((i) => i.state === 'running') };
}

// --- CLI -------------------------------------------------------------------

function main() {
  const argv = process.argv.slice(2);
  const cmd = argv[0];
  if (!cmd || cmd === '--help' || cmd === '-h') {
    console.log(HELP);
    process.exit(cmd ? 0 : 1);
  }
  const rest = argv.slice(1);

  if (cmd === 'list') {
    const { flags } = parseArgs(rest, {});
    const root = findRepoRoot(import.meta.url, flags.root);
    let items = loadQueue(root).items;
    if (flags.state) items = items.filter((i) => i.state === flags.state);
    if (flags.json) {
      console.log(JSON.stringify(items, null, 2));
    } else {
      printTable(items, [
        { key: 'id', header: 'id' },
        { key: 'ticket', header: 'ticket' },
        { key: 'kind', header: 'kind' },
        { key: 'agent', header: 'agent' },
        { key: 'branch', header: 'branch' },
        { key: 'state', header: 'state' },
        { key: 'sha', header: 'sha' },
        { key: 'note', header: 'note' },
      ]);
    }
    return;
  }

  if (cmd === 'add') {
    const { flags, positional } = parseArgs(rest, {});
    const root = findRepoRoot(import.meta.url, flags.root);
    const ticket = positional[0];
    try {
      const item = addItem(root, { ticket, kind: flags.kind, agent: flags.agent, branch: flags.branch, note: flags.note });
      console.log(flags.json ? JSON.stringify(item, null, 2) : `${item.id}: ${item.ticket} queued`);
    } catch (e) {
      fail(e.message);
    }
    return;
  }

  if (cmd === 'set') {
    const { flags, positional } = parseArgs(rest, {});
    const root = findRepoRoot(import.meta.url, flags.root);
    const [idOrTicket, state] = positional;
    if (!idOrTicket || !state) fail('usage: queue set <id|ticket> <state> [--sha x] [--note n]');
    try {
      const item = setItem(root, idOrTicket, state, { sha: flags.sha, note: flags.note });
      console.log(flags.json ? JSON.stringify(item, null, 2) : `${item.id}: ${item.ticket} -> ${item.state}`);
    } catch (e) {
      fail(e.message);
    }
    return;
  }

  if (cmd === 'next') {
    const { flags } = parseArgs(rest, {});
    const root = findRepoRoot(import.meta.url, flags.root);
    const item = nextQueued(root, { agent: flags.agent, kind: flags.kind });
    if (flags.json) {
      console.log(JSON.stringify(item, null, 2));
    } else {
      console.log(item ? `${item.id}: ${item.ticket} (${item.kind}/${item.agent}) ${item.branch}` : '(none queued)');
    }
    return;
  }

  if (cmd === 'rm') {
    const { flags, positional } = parseArgs(rest, {});
    const root = findRepoRoot(import.meta.url, flags.root);
    const id = positional[0];
    if (!id) fail('usage: queue rm <id>');
    try {
      const item = removeItem(root, id);
      console.log(flags.json ? JSON.stringify(item, null, 2) : `${item.id}: removed`);
    } catch (e) {
      fail(e.message);
    }
    return;
  }

  if (cmd === 'render') {
    const { flags } = parseArgs(rest, {});
    const root = findRepoRoot(import.meta.url, flags.root);
    const data = loadQueue(root);
    renderMd(root, data);
    console.log(queueMdPath(root));
    return;
  }

  fail(`unknown command '${cmd}' — see --help`);
}

const isMain = process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
if (isMain) main();
