// GRAIN'S OWN STATE IS NEVER PART OF THE ARCHITECTURE IT PROPOSES (ticket 116, part 3).
//
// `grain export` filters grain's own store out of the file universe it mines (`HARD_EXCL`), but the proposal
// renderer resolved its own file list with a bare `git ls-files` and filtered nothing. That is invisible on a
// repository that has never committed `.grain/` — and grain's own `.grain/.gitignore` says everything in
// `.grain/` OTHER than `cache/` is meant to be committed, so an adopter who follows that ends up with grain's
// bookkeeping proposed back at them as a type of their architecture ("`.grain` holds 2 tracked files nothing
// else in this proposal claims"). The same holds for `.yggdrasil-proposal/`, the staging tree `grain propose`
// itself writes: an adopter who commits a proposal while reviewing it gets the proposal proposed on.
//
// The fixture commits both, exactly as an adopter would.
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const PROPOSE = join(here, 'stress', 'propose.mjs');

let tmp, repo, out;

function buildFixture(root, env) {
  mkdirSync(root, { recursive: true });
  const w = (rel, content) => { const p = join(root, rel); mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, content); };
  for (const n of ['alpha', 'beta', 'gamma', 'delta', 'epsilon']) {
    w(`src/${n}Task.ts`, `import { join } from 'node:path';\nexport function run(base: string): string {\n  return join(base, '${n}');\n}\n`);
  }
  w('README.md', '# fixture\n');
  // what grain itself writes on its first run and declares committable
  w('.grain/.gitignore', '# generated by grain — the cache is disposable; everything else in .grain/ is meant to be committed\ncache/\n');
  w('.grain/seeds.jsonl', '{"note":"a maintainer seed"}\n');
  // and the staging tree `grain propose` writes, committed by an adopter mid-review
  w('.yggdrasil-proposal/PROPOSAL.md', '# a proposal under review\n');
  w('.yggdrasil-proposal/.yggdrasil/yg-config.yaml', 'version: 1\n');
  execFileSync('git', ['-C', root, 'init', '-q', '-b', 'main'], { env });
  execFileSync('git', ['-C', root, 'add', '-A', '-f'], { env });
  execFileSync('git', ['-C', root, 'commit', '-q', '-m', 'fixture'], { env });
}

before(() => {
  tmp = mkdtempSync(join(tmpdir(), 'propose-own-state-'));
  repo = join(tmp, 'repo');
  out = join(tmp, 'proposal');
  const env = {
    ...process.env, HOME: tmp,
    GIT_AUTHOR_NAME: 'T', GIT_AUTHOR_EMAIL: 't@x', GIT_COMMITTER_NAME: 'T', GIT_COMMITTER_EMAIL: 't@x',
    GIT_AUTHOR_DATE: '2026-01-10T12:00:00Z', GIT_COMMITTER_DATE: '2026-01-10T12:00:00Z',
  };
  buildFixture(repo, env);
  const r = spawnSync('node', [PROPOSE, repo, out, '--no-history', '--quiet'], { encoding: 'utf8', maxBuffer: 1 << 28 });
  assert.equal(r.status, 0, r.stderr);
});
after(() => { try { rmSync(tmp, { recursive: true, force: true }); } catch { /* best effort */ } });

test('the fixture really does track grain\'s own state, which is the case this closes', () => {
  const tracked = execFileSync('git', ['-C', repo, 'ls-files'], { encoding: 'utf8' }).split('\n');
  assert.ok(tracked.includes('.grain/seeds.jsonl'));
  assert.ok(tracked.includes('.yggdrasil-proposal/PROPOSAL.md'));
});

test('grain\'s own store and its staging tree are never a type, a node or an uncovered group', () => {
  const j = JSON.parse(readFileSync(join(out, 'proposal.json'), 'utf8'));
  for (const row of j.evidence) {
    assert.ok(!/(^|[^A-Za-z0-9-])\.?grain(\/|$)/.test(String(row.dir ?? '')), `\`${row.dir}\` was proposed as ${row.kind} ${row.id}`);
    assert.ok(!/yggdrasil-proposal/.test(`${row.id} ${row.evidence}`), `the staging tree reached ${row.kind} ${row.id}: ${row.evidence}`);
    assert.ok(!/`\.grain`/.test(String(row.evidence)), `grain's own store reached ${row.kind} ${row.id}: ${row.evidence}`);
  }
  const ids = j.evidence.map(e => e.id);
  assert.ok(!ids.includes('grain'), 'grain\'s own store became a node type');
  assert.ok(!ids.includes('yggdrasil-proposal'), 'the staging tree became a node type');
  // and neither is counted among the files the proposal claims to describe: 6 sources, not 10
  assert.equal(j.files, 6, `expected the six real files, got ${j.files}`);
});

test('nothing about either directory reaches the documents a maintainer reads', () => {
  for (const f of readdirSync(out)) {
    if (!f.endsWith('.md')) continue;
    const text = readFileSync(join(out, f), 'utf8');
    assert.ok(!text.includes('.yggdrasil-proposal'), `${f} names the staging tree`);
    assert.ok(!/`\.grain`|\.grain\/\*\*/.test(text), `${f} names grain's own store`);
  }
});
