// `grain rules` renders a standalone Markdown document over the SAME model data `report()` prints — for a reader
// with no terminal and no grain plugin (a human maintainer, or a coding tool without this plugin installed).
// Built against the shared deterministic fixture (tests/fixtures/build-fixture.mjs) so its known, well-understood
// established conventions (the `@Handler` decorator convention on src/handlers/*.handler.ts among them) give a
// real, reproducible thing to assert on.
import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const BIN = join(here, '..', 'bin', 'grain.mjs');
const BUILDER = join(here, '..', '..', '..', 'tests', 'fixtures', 'build-fixture.mjs');
let tmp, repo;
const grain = (args, opts = {}) => { const r = spawnSync('node', [BIN, ...args], { cwd: opts.cwd || repo, encoding: 'utf8' });
  return { out: (r.stdout || '').replace(/\n$/, ''), err: r.stderr, code: r.status }; };

before(() => { tmp = mkdtempSync(join(tmpdir(), 'grain-rules-')); repo = join(tmp, 'fixture'); execFileSync('node', [BUILDER, repo], { stdio: 'pipe' }); });
after(() => { rmSync(tmp, { recursive: true, force: true }); });

test('grain rules prints a Markdown document to stdout: staleness header with a real sha, a known convention with its exemplar, and the architecture section', () => {
  const { out, code, err } = grain(['rules', '--top', '40']);
  assert.equal(code, 0, err);
  assert.match(out, /^# fixture — established conventions$/m, out);
  assert.match(out, /Generated by `grain rules` as of commit `[0-9a-f]{7}` on \d{4}-\d{2}-\d{2} — this file is a snapshot, not a live query/, out);
  assert.match(out, /recompute with `grain rules --out <this file>` after the code moves/, out);
  // a known established convention, with its real exemplar path — the same fact `report` finds (grain.test.mjs
  // asserts the identical phrase against the same fixture)
  assert.match(out, /types here are annotated with `@Handler`/, out);
  assert.match(out, /\| `src\/handlers\/[a-z]+\.handler\.ts:\d+` \|/, out);
  // no live-query "how is this changing" section — a generated reference document is "what to copy right now"
  assert.doesNotMatch(out, /== drift|## Drift/, out);
  // the fixture's own directory layout produces a real module graph
  assert.match(out, /^## Architecture$/m, out);
  assert.match(out, /\d+ modules · \d+ directed dependencies · \d+ cycle\(s\)/, out);
  assert.match(out, /- `src\/handlers\/` → .*`src\/(core|services)\/` \(\d+\)/, out);
  // the freshness stamp goes to stderr, not stdout — so `grain rules > file.md` is never corrupted
  assert.match(err, /\[grain\] as of [0-9a-f]{7}$/m, err);
  assert.doesNotMatch(out, /\nas of [0-9a-f]{7}$/, 'the stamp must not leak onto stdout');
});

test('grain rules --out <path> writes the file and answers with a short confirmation, not the whole document', () => {
  const outPath = join(tmp, 'CONVENTIONS.md');
  const stdoutDoc = grain(['rules', '--top', '40']).out;
  const { out, code, err } = grain(['rules', '--top', '40', '--out', outPath]);
  assert.equal(code, 0, err);
  assert.match(out, /^wrote \d+ convention\(s\) to .*CONVENTIONS\.md$/m, out);
  assert.match(out, /\nas of [0-9a-f]{7}$/, out);
  assert.ok(!out.includes('# fixture — established conventions'), 'the confirmation must not also dump the document to stdout');
  assert.ok(existsSync(outPath));
  const written = readFileSync(outPath, 'utf8').replace(/\n$/, '');
  assert.equal(written, stdoutDoc, 'the written file must match what plain stdout output would have been');
});

test('a relative --out path resolves against the cwd, the same convention `export --out` already uses', () => {
  const rel = 'CONVENTIONS-rel.md';
  const { out, code } = grain(['rules', '--out', rel]);
  assert.equal(code, 0, out);
  assert.ok(existsSync(join(repo, rel)));
});

test('an empty/unbuilt model does not crash: a plain non-git directory with no source files still prints a header', () => {
  const empty = mkdtempSync(join(tmpdir(), 'grain-rules-empty-'));
  try {
    writeFileSync(join(empty, 'README.txt'), 'nothing to parse here\n');
    const r = spawnSync('node', [BIN, 'rules'], { cwd: empty, encoding: 'utf8' });
    assert.equal(r.status, 0, r.stdout + r.stderr);
    assert.match(r.stdout, /established conventions/);
    assert.match(r.stdout, /Generated by `grain rules` as of commit `no-git`/);
  } finally { rmSync(empty, { recursive: true, force: true }); }
});
